'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, X, Copy, Check } from 'lucide-react';
import type { Profile, ClientProfile, ClientHabit, Habit, CoachNote } from '@/lib/types';

interface CoachingSummaryProps {
  profile: Profile;
  clientProfile: ClientProfile;
  activeHabit: (ClientHabit & { habit?: Habit }) | null;
  pastHabits: (ClientHabit & { habit?: Habit })[];
  notes: CoachNote[];
}

export default function CoachingSummary({
  profile,
  clientProfile,
  activeHabit,
  pastHabits,
  notes,
}: CoachingSummaryProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const streakDays = activeHabit?.current_streak ?? 0;
  const cycleDays = activeHabit?.habit?.cycle_days ?? 14;
  const completionPct =
    cycleDays > 0
      ? Math.round(((activeHabit?.total_completions ?? 0) / cycleDays) * 100)
      : 0;

  const goalLabels: Record<string, string> = {
    fat_loss: 'Fat Loss',
    muscle_gain: 'Muscle Gain',
    maintenance: 'Maintenance',
    recomp: 'Recomposition',
    endurance: 'Endurance',
    health: 'Health',
  };

  function generateSummary(): string {
    const lines: string[] = [];
    lines.push('========================================');
    lines.push('  trophe --- Coaching Summary');
    lines.push('========================================');
    lines.push('');
    lines.push(`Client: ${profile.full_name}`);
    lines.push(`Date: ${today}`);
    lines.push(`Goal: ${clientProfile.goal ? goalLabels[clientProfile.goal] || clientProfile.goal : 'Not set'}`);
    lines.push('');

    // Active habit
    if (activeHabit?.habit) {
      lines.push(`Current Habit: ${activeHabit.habit.emoji} ${activeHabit.habit.name_en} --- Day ${streakDays}/${cycleDays}`);
      lines.push(`Completion: ${completionPct}%`);
      lines.push(`Best Streak: ${activeHabit.best_streak} days`);
    } else {
      lines.push('Current Habit: None assigned');
    }
    lines.push('');

    // Body stats
    lines.push('--- Body Stats ---');
    lines.push(
      `Weight: ${clientProfile.weight_kg ?? '---'}kg | Height: ${clientProfile.height_cm ?? '---'}cm`
    );
    lines.push(`BMR: ${clientProfile.bmr ?? '---'} | TDEE: ${clientProfile.tdee ?? '---'}`);
    lines.push('');

    // Macros
    lines.push('--- Macro Targets ---');
    lines.push(
      `${clientProfile.target_calories ?? '---'}kcal | ${clientProfile.target_protein_g ?? '---'}g P | ${clientProfile.target_carbs_g ?? '---'}g C | ${clientProfile.target_fat_g ?? '---'}g F`
    );
    lines.push(`Water: ${clientProfile.target_water_ml ?? '---'}ml | Fiber: ${clientProfile.target_fiber_g ?? '---'}g`);
    lines.push('');

    // Recent notes (last 5)
    const recentNotes = notes.slice(0, 5);
    if (recentNotes.length > 0) {
      lines.push('--- Recent Notes ---');
      recentNotes.forEach((n) => {
        const date = new Date(n.created_at).toLocaleDateString('en-US', {
          month: 'short',
          day: 'numeric',
        });
        lines.push(`  [${date}] ${n.note}`);
      });
      lines.push('');
    }

    // Habit history
    if (pastHabits.length > 0) {
      lines.push('--- Habit History ---');
      pastHabits.forEach((h) => {
        const status = h.status === 'completed' ? 'Completed' : h.status === 'paused' ? 'Paused' : h.status;
        lines.push(
          `  ${h.habit?.emoji ?? ''} ${h.habit?.name_en ?? 'Unknown'}: ${status} (${h.total_completions} days, best streak: ${h.best_streak})`
        );
      });
      lines.push('');
    }

    lines.push('========================================');
    lines.push('  Generated by trophe');
    lines.push('========================================');

    return lines.join('\n');
  }

  async function handleCopy() {
    const text = generateSummary();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="text-xs btn-ghost !py-1.5 !px-3 flex items-center gap-1"
      >
        <FileText size={12} /> Export Summary
      </button>

      <AnimatePresence>
        {open && (
          <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/60 backdrop-blur-sm p-4">
            <motion.div
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 40 }}
              className="glass-elevated p-5 w-full max-w-lg max-h-[80vh] flex flex-col"
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold text-stone-100 flex items-center gap-2">
                  <FileText size={16} className="text-[#D4A853]" />
                  Coaching Summary
                </h3>
                <button
                  onClick={() => setOpen(false)}
                  className="text-stone-500 hover:text-stone-300"
                >
                  <X size={18} />
                </button>
              </div>

              <pre className="flex-1 overflow-y-auto text-xs text-stone-300 bg-stone-900/80 rounded-xl p-4 font-mono whitespace-pre-wrap leading-relaxed mb-4">
                {generateSummary()}
              </pre>

              <button
                onClick={handleCopy}
                className="btn-gold w-full flex items-center justify-center gap-2 py-3"
              >
                {copied ? (
                  <>
                    <Check size={16} /> Copied!
                  </>
                ) : (
                  <>
                    <Copy size={16} /> Copy to Clipboard
                  </>
                )}
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}
