INSERT INTO "food_database" (
  "name", "name_el", "name_es",
  "calories_per_100g", "protein_per_100g", "carbs_per_100g", "fat_per_100g", "fiber_per_100g",
  "default_serving_grams", "default_serving_unit", "common_units", "category", "source", "popularity"
) VALUES
  ('Arepa', NULL, 'Arepa colombiana; arepa paisa; arepa de maiz', 220, 5.2, 45, 2.4, 4.5, 80, 'piece', '[{"name":"piece","grams":80},{"name":"small","grams":55},{"name":"large","grams":110}]', 'colombian', 'seed', 90),
  ('Arepa con queso', NULL, 'Arepa con queso; arepa rellena de queso; cheese arepa', 260, 8.5, 34, 9.5, 3.2, 140, 'piece', '[{"name":"piece","grams":140},{"name":"small","grams":100}]', 'colombian', 'seed', 95),
  ('Arepa de choclo con queso', NULL, 'Arepa de choclo; arepa dulce con queso; sweet corn arepa', 255, 7, 38, 8, 3, 140, 'piece', '[{"name":"piece","grams":140}]', 'colombian', 'seed', 88),
  ('Almojabana', NULL, 'Almojabana; almojábana; pan de queso colombiano', 325, 8.8, 38, 15, 1.2, 80, 'piece', '[{"name":"piece","grams":80}]', 'colombian', 'seed', 86),
  ('Pandebono', NULL, 'Pandebono; pan de bono; Colombian cheese bread', 315, 8.5, 40, 13, 1.1, 70, 'piece', '[{"name":"piece","grams":70}]', 'colombian', 'seed', 86),
  ('Bunuelo colombiano', NULL, 'Buñuelo; bunuelo; Colombian cheese fritter', 330, 7.5, 36, 17, 1, 70, 'piece', '[{"name":"piece","grams":70}]', 'colombian', 'seed', 85),
  ('Empanada colombiana', NULL, 'Empanada; empanada de carne; empanada bogotana', 285, 8, 30, 14, 2.2, 100, 'piece', '[{"name":"piece","grams":100},{"name":"small","grams":70}]', 'colombian', 'seed', 90),
  ('Tamal colombiano', NULL, 'Tamal; tamal bogotano; tamal tolimense', 185, 8, 22, 7, 2.5, 300, 'piece', '[{"name":"piece","grams":300},{"name":"serving","grams":300}]', 'colombian', 'seed', 86),
  ('Changua bogotana', NULL, 'Changua; changua con huevo; sopa de leche bogotana', 70, 4.5, 6.5, 3, 0.2, 320, 'bowl', '[{"name":"bowl","grams":320},{"name":"cup","grams":240}]', 'colombian', 'seed', 88),
  ('Ajiaco bogotano', NULL, 'Ajiaco; ajiaco santafereño; Colombian chicken potato soup', 95, 7.5, 12, 2.2, 2, 450, 'bowl', '[{"name":"bowl","grams":450},{"name":"serving","grams":450}]', 'colombian', 'seed', 92),
  ('Caldo de costilla', NULL, 'Caldo de costilla; soup de costilla; beef rib soup', 72, 6.5, 6.5, 2.5, 0.8, 400, 'bowl', '[{"name":"bowl","grams":400}]', 'colombian', 'seed', 84),
  ('Sancocho colombiano', NULL, 'Sancocho; sancocho de gallina; Colombian stew', 105, 8, 13, 2.7, 2, 450, 'bowl', '[{"name":"bowl","grams":450},{"name":"serving","grams":450}]', 'colombian', 'seed', 86),
  ('Bandeja paisa', NULL, 'Bandeja paisa; Colombian platter; beans rice chicharron', 175, 9, 17, 8, 3, 700, 'plate', '[{"name":"plate","grams":700},{"name":"serving","grams":700}]', 'colombian', 'seed', 93),
  ('Arroz con pollo colombiano', NULL, 'Arroz con pollo; rice with chicken Colombian', 150, 8, 21, 4, 1.5, 350, 'serving', '[{"name":"serving","grams":350},{"name":"plate","grams":350}]', 'colombian', 'seed', 87),
  ('Calentado colombiano', NULL, 'Calentado; calentao; rice beans eggs leftovers', 155, 7, 22, 4.5, 3.2, 350, 'plate', '[{"name":"plate","grams":350},{"name":"serving","grams":350}]', 'colombian', 'seed', 86),
  ('Frijoles rojos colombianos', NULL, 'Frijoles rojos; frijoles cargamanto; red beans', 118, 7.8, 20, 0.8, 7, 180, 'cup', '[{"name":"cup","grams":180},{"name":"serving","grams":180}]', 'colombian', 'seed', 84),
  ('Patacon', NULL, 'Patacon; patacón; tostón; fried green plantain', 300, 1.7, 45, 12, 3.5, 120, 'piece', '[{"name":"piece","grams":120},{"name":"small","grams":80}]', 'colombian', 'seed', 82),
  ('Platano maduro frito', NULL, 'Plátano maduro frito; fried sweet plantain; tajadas', 255, 1.3, 45, 8.5, 2.5, 120, 'serving', '[{"name":"serving","grams":120},{"name":"piece","grams":90}]', 'colombian', 'seed', 84),
  ('Chicharron colombiano', NULL, 'Chicharrón; chicharron; crispy pork belly', 520, 28, 0, 45, 0, 100, 'piece', '[{"name":"piece","grams":100},{"name":"serving","grams":100}]', 'colombian', 'seed', 82),
  ('Lechona', NULL, 'Lechona; lechona tolimense; pork rice peas', 205, 11, 18, 10, 2, 300, 'serving', '[{"name":"serving","grams":300},{"name":"plate","grams":300}]', 'colombian', 'seed', 80),
  ('Sobrebarriga en salsa', NULL, 'Sobrebarriga; flank steak Colombian sauce', 190, 20, 4, 10, 0.7, 220, 'serving', '[{"name":"serving","grams":220}]', 'colombian', 'seed', 78),
  ('Carne desmechada', NULL, 'Carne desmechada; shredded beef; ropa vieja', 180, 24, 2, 8, 0.5, 150, 'serving', '[{"name":"serving","grams":150}]', 'colombian', 'seed', 80),
  ('Papa criolla', NULL, 'Papa criolla; Colombian yellow potato', 87, 2, 20, 0.1, 2.2, 150, 'serving', '[{"name":"serving","grams":150},{"name":"cup","grams":150}]', 'colombian', 'seed', 80),
  ('Hogao', NULL, 'Hogao; guiso colombiano; tomato onion sauce', 55, 1.2, 7, 2.5, 1.8, 40, 'tbsp', '[{"name":"tbsp","grams":15},{"name":"serving","grams":40}]', 'colombian', 'seed', 76),
  ('Aguapanela', NULL, 'Aguapanela; agua panela; panela drink', 38, 0, 9.5, 0, 0, 250, 'glass', '[{"name":"glass","grams":250},{"name":"cup","grams":240}]', 'colombian', 'seed', 80),
  ('Chocolate santafereño', NULL, 'Chocolate con queso; Colombian hot chocolate; chocolate bogotano', 95, 3.5, 13, 3.5, 1, 250, 'cup', '[{"name":"cup","grams":250},{"name":"mug","grams":300}]', 'colombian', 'seed', 82),
  ('Jugo de lulo', NULL, 'Jugo de lulo; lulo juice; lulada light', 48, 0.6, 11.5, 0.2, 1, 300, 'glass', '[{"name":"glass","grams":300}]', 'colombian', 'seed', 79),
  ('Jugo de mora en agua', NULL, 'Jugo de mora; blackberry juice Colombian', 45, 0.5, 10.5, 0.2, 1.5, 300, 'glass', '[{"name":"glass","grams":300}]', 'colombian', 'seed', 78),
  ('Oblea con arequipe', NULL, 'Oblea; oblea con arequipe; Colombian wafer dessert', 360, 5, 62, 10, 1.5, 80, 'piece', '[{"name":"piece","grams":80}]', 'colombian', 'seed', 78),
  ('Chocoramo', NULL, 'Chocoramo; ponque colombiano cubierto de chocolate', 395, 4.5, 58, 16, 1.5, 65, 'piece', '[{"name":"piece","grams":65}]', 'colombian', 'seed', 78)
ON CONFLICT ("name", "source") DO UPDATE SET
  "name_es" = EXCLUDED."name_es",
  "calories_per_100g" = EXCLUDED."calories_per_100g",
  "protein_per_100g" = EXCLUDED."protein_per_100g",
  "carbs_per_100g" = EXCLUDED."carbs_per_100g",
  "fat_per_100g" = EXCLUDED."fat_per_100g",
  "fiber_per_100g" = EXCLUDED."fiber_per_100g",
  "default_serving_grams" = EXCLUDED."default_serving_grams",
  "default_serving_unit" = EXCLUDED."default_serving_unit",
  "common_units" = EXCLUDED."common_units",
  "category" = EXCLUDED."category",
  "popularity" = EXCLUDED."popularity";
