from pathlib import Path
import json,hashlib,subprocess,datetime,shutil,zipfile
ROOT=Path('/Volumes/SSD/TROPHE_DUAL_AGENTS_R1');J=ROOT/'factory-work/r2/jobs';D=ROOT/'reviews/ag2/r2-incline-dumbbell-720-02'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
roles={'motion':'r2-incline-motion-v2-02','garment_fit':'r2-incline-garment-v2-02','garment_binding':'r2-incline-v2-cloth-bind-01','local_fold':'r2-incline-v2-fold-02','master':'r2-incline-v2-shell-gate-01','qa':'r2-incline-v2-qa-02','photos':'r2-incline-v2-photos-05','fixed':'r2-incline-v2-fixed-02','orbit':'r2-incline-v2-orbit-01','comparison':'r2-incline-v1-comparison-01','orbit_regression':'r2-incline-v2-orbit-regression-01'}
commits=json.loads((ROOT/'factory-work/r2/reference-incline-v2/recipe-commits.json').read_text());provenance={}
for role,jid in roles.items():
 job=J/jid;obs=json.loads((job/'observed.json').read_text());assert obs['terminal']['exit_code']==0 and not obs['process_alive'] and obs['task_state']=='Ready',jid
 result=json.loads((job/'output/result.json').read_text());commit=commits[jid]
 for module,digest in result['recipe_modules'].items():
  contents=subprocess.check_output(['git','-C',str(ROOT/'code/ag2'),'show',commit+':tools/media-factory/r2/'+module]);assert hashlib.sha256(contents).hexdigest()==digest,(jid,module)
 provenance[role]={'job':str(job),'recipe_commit':commit,'config_sha256':sha(job/'config.json'),'result_sha256':sha(job/'output/result.json'),'result':result,'observed_terminal':obs}
assert not D.exists();D.mkdir()
for p in (J/roles['photos']/'output').glob('*.png'):shutil.copy2(p,D/p.name)
for role in ['fixed','orbit']:
 for p in (J/roles[role]/'output').glob('frame-*.png'):shutil.copy2(p,D/(role+'-'+p.name))
for name,role,file in [('motion-refinement.json','motion','motion-refinement.json'),('garment-refinement.json','garment_fit','garment-refinement.json'),('garment-binding.json','garment_binding','garment-surface-bind.json'),('pose-fold.json','local_fold','pose-fold.json'),('shell-gate.json','master','shell-gate.json'),('qa.json','qa','qa.json'),('handle-contact.json','photos','handle-contact.json'),('orbit-framing.json','orbit','framing-gate.json'),('fixed-framing.json','fixed','framing-gate.json'),('orbit-regression.json','orbit_regression','render-regression.json')]:shutil.copy2(J/roles[role]/'output'/file,D/name)
videos={}
for role,n,duration in [('orbit',540,18),('fixed',180,6)]:
 v=D/('incline-dumbbell-'+role+'-720p-v2.mp4');shutil.copy2(J/roles[role]/'output/motion.mp4',v)
 probe=json.loads(subprocess.check_output(['/opt/homebrew/bin/ffprobe','-v','error','-show_entries','stream=codec_name,width,height,r_frame_rate,nb_frames:format=duration','-of','json',str(v)]));st=probe['streams'][0]
 assert (st['width'],st['height'],st['r_frame_rate'],int(st['nb_frames']))==(1280,720,'30/1',n);assert abs(float(probe['format']['duration'])-duration)<.01
 frames=subprocess.check_output(['/opt/homebrew/bin/ffmpeg','-v','error','-i',str(v),'-f','framemd5','-'],text=True);distinct=len(set(x.rsplit(',',1)[-1].strip() for x in frames.splitlines() if not x.startswith('#')));assert distinct>(500 if role=='orbit' else 150)
 videos[role]={'path':str(v),'sha256':sha(v),'probe':probe,'distinct_frames':distinct}
q=json.loads((D/'qa.json').read_text());h=json.loads((D/'handle-contact.json').read_text())
summary={'grip_drift_max_m':max(v['drift_m'] for r in q['rows'] for v in r['sides'].values()),'surface_step_max_m':max(r['surface_step_max_m'] for r in q['rows']),'closure_surface_m':q['closure_surface_m'],'non_handle_crossing_frames':sum(any('handle' not in n for n in r['equipment_crossings']) for r in q['rows']),'skin_intersection_pairs':sum(v['intersection_pairs'] for r in q['rows'] if 'skin' in r for v in r['skin'].values()),'garment_crossings':{n:max(r.get('cloth',{}).get(n,{}).get('body_crossing_count',0) for r in q['rows']) for n in ['SportsTank','SportsShorts']},'critical_frames':[r['frame'] for r in q['rows'] if 'skin' in r],'handle_radial_penetration_max_m':max(v['maximum_radial_penetration_m'] for r in h for v in r['handles'].values()),'supports':q['rows'][0]['supports']}
assert summary['grip_drift_max_m']<.001 and summary['non_handle_crossing_frames']==0 and summary['surface_step_max_m']<.025
summary['skin_affected_frames']=[r['frame'] for r in q['rows'] if any(v['intersection_pairs'] for v in r.get('skin',{}).values())]
summary['cloth_self_affected_frames']=[r['frame'] for r in q['rows'] if any(v.get('self_crossing_pairs',0) for v in r.get('cloth',{}).values())]
summary['garment_body_affected_frames']=[r['frame'] for r in q['rows'] if any(v['body_crossing_count'] for v in r.get('cloth',{}).values())]
summary['technical_passed']=not(summary['skin_affected_frames'] or summary['cloth_self_affected_frames'] or summary['garment_body_affected_frames'])
(D/'qa-summary.json').write_text(json.dumps(summary,indent=2));(D/'provenance.json').write_text(json.dumps(provenance,indent=2))
master=J/roles['master']/'output/incline.blend';review_observation=ROOT/'factory-work/r2/reference-incline-v2/final-visual-observation.json';assert review_observation.exists();shutil.copy2(review_observation,D/'visual-observation.json')
index={'id':'incline-dumbbell-male-r2-review-20260906-02','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'state':'PRIVATE_TECHNICAL_HOLD' if not summary['technical_passed'] else 'PRIVATE_REVIEW_READY','human_reviews':{'visual':'pending','technique':'pending'},'asset_ready':False,'published':False,'master':{'path':str(master),'sha256':sha(master)},'recipe_commit':commits[roles['master']],'qa_render_commit':commits[roles['orbit']],'parent_review':'reviews/ag2/r2-incline-dumbbell-720-01','parent_video_sha256':'1296a70843a3414ff4df6418abe5500a5797ffd228f58f1eeb0e8088bc0206cd','videos':videos,'qa':summary,'photos':[{'path':str(p),'sha256':sha(p)} for p in sorted(D.glob('*.png'))],'provenance_sha256':sha(D/'provenance.json'),'reference':json.loads((ROOT/'control/ag2/status.json').read_text())['incline_v2']['reference'],'limits':['Authored skin/muscle response, no force simulation or human technique certification','Actual contact and surface observations are scoped to recorded checks; human reviews pending']}
fingerprint={'master_sha256':sha(master),'render_configs':{role:{k:v for k,v in json.loads((J/roles[role]/'config.json').read_text()).items() if k not in ['id','animation_source','comparison_source']} for role in ['fixed','orbit']},'render_recipe_modules':{role:provenance[role]['result']['recipe_modules'] for role in ['fixed','orbit']},'blender':provenance['orbit']['result']['blender'],'mpfb':'2.0.17'}
index['build_key']=hashlib.sha256(json.dumps(fingerprint,sort_keys=True,separators=(',',':')).encode()).hexdigest()
index['source_fingerprint']=sha(master)
(D/'build-fingerprint.json').write_text(json.dumps(fingerprint,indent=2))
(D/'index.json').write_text(json.dumps(index,indent=2))
html='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Press inclinado · V2</title><style>body{background:#15171b;color:#eceef1;font:16px system-ui;max-width:1100px;margin:auto;padding:24px}video,img{width:100%;border-radius:12px}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}h1{font-size:28px}p{line-height:1.5}a{color:#94d6fc}figure{margin:0}figcaption{padding:8px 0 20px;color:#b9c1cc}</style><h1>Press inclinado con mancuernas · V2</h1><p>18 segundos · giro continuo de360° · tres repeticiones ·720p ·30fps. Bajada hacia el pecho superior, mancuernas niveladas y camiseta deportiva con cuello cerrado. Revisiones humanas pendientes. Diagnóstico con pliegue local de codo todavía pendiente de cierre técnico; no aprobado para publicar.</p><video controls playsinline preload="metadata" poster="frame-091.png" src="incline-dumbbell-orbit-720p-v2.mp4"></video><h2>Cámara fija · un ciclo de6 segundos</h2><video controls playsinline preload="metadata" poster="frame-001.png" src="incline-dumbbell-fixed-720p-v2.mp4"></video><h2>Recorrido y agarre</h2><section>'''
for name,label in [('frame-001.png','Extensión'),('frame-091.png','Máxima flexión'),('frame-046.png','Descenso'),('side-091.png','Vista lateral y apoyo'),('hands-001.png','Agarre en extensión'),('hands-091.png','Agarre en flexión')]:html+=f'<figure><img src="{name}" loading="lazy"><figcaption>{label}</figcaption></figure>'
html+='</section><p><a href="incline-video-fotos-v2.zip">Descargar vídeos y fotos</a> · <a href="qa-summary.json">Comprobaciones</a> · <a href="index.json">Identidad y fuentes</a></p><p>La escena conserva el banco de30°. El movimiento se comparó con la grabación real aportada. La forma muscular es de autoría y sigue abierta a revisión; no representa una simulación de fuerzas.</p>'
(D/'revision.html').write_text(html)
shutil.copy2(ROOT/'factory-work/r2/reference-incline-v2/REFERENCE_SCOPE.md',D/'REFERENCE_SCOPE.md')
for name in ['frame-001.png','frame-100.png']:
 shutil.copy2(J/'r2-incline-v1-comparison-01/output'/name,D/('v1-'+name))
html+=("<h2>Comparación V1 / V2 · misma cámara y luz</h2><section><figure><img src='v1-frame-001.png'><figcaption>V1 · extensión</figcaption></figure><figure><img src='fixed-frame-001.png'><figcaption>V2 · extensión</figcaption></figure><figure><img src='v1-frame-100.png'><figcaption>V1 · máxima flexión</figcaption></figure><figure><img src='fixed-frame-091.png'><figcaption>V2 · máxima flexión, mayor profundidad y prenda nueva</figcaption></figure></section>")
(D/'revision.html').write_text(html)
(D/'REPORT.md').write_text('# Press inclinado · V2\n\n18s de órbita360°,3repeticiones de6s.720p30fps nativos. Descenso ampliado, antebrazos casi verticales, mancuernas horizontales de mayor diámetro. Camiseta ajustada con cuello y mangas cortas, fuente MPFB CC0, bordes terminados, shorts y zapatillas conservados.\n\nSe corrigió una pérdida de transformación reflejada del ancla izquierda al convertirla solo a cuaternión; se preserva ahora la matriz completa. No se adoptaron los experimentos de escala o transformación del antebrazo ni la variante de bisagra del codo. El pliegue local se suaviza mediante una corrección nativa limitada a la región comprobada, pero conserva cruces técnicos pendientes. El agarre y las restricciones nativas calibradas originales permanecen.\n\nLa referencia real del usuario está identificada por hash en index.json. Referencia complementaria de ejecución: https://www.nasm.org/resource-center/exercise-library/two-arm-incline-dumbbell-chest-press . Su ángulo indicado es45°;30° es la elección de esta escena.\n\nVer qa-summary.json y visual-observation.json para resultados y límites. Revisiones humanas visual/técnica pendientes. Si persisten cruces, este es un diagnóstico con HOLD técnico; HD y paquete de consumo permanecen retenidos. Privado, sin publicación ni ASSET_READY. V1 intacto.\n')
(D/'SHA256SUMS').write_text(''.join(sha(p)+'  '+p.name+'\n' for p in sorted(D.iterdir()) if p.is_file()))
with zipfile.ZipFile(D/'incline-video-fotos-v2.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted(D.iterdir()):
  if p.suffix!='.zip':z.write(p,p.name)
print(json.dumps({'directory':str(D),'index_sha256':sha(D/'index.json'),'videos':videos,'qa':summary},indent=2))
