// ═══════════════════════════════════════════════
// τροφή (Trophē) — Comprehensive Food Database Seed
// 200+ foods: Kavdas plan foods + Greek/Mediterranean + global staples
// All values per 100g, sourced from USDA FoodData Central
// ═══════════════════════════════════════════════

export interface FoodSeedEntry {
  name: string;
  name_el: string;
  name_es: string;
  calories_per_100g: number;
  protein_per_100g: number;
  carbs_per_100g: number;
  fat_per_100g: number;
  fiber_per_100g: number;
  default_serving_grams: number;
  default_serving_unit: string;
  common_units: { name: string; grams: number }[];
  category: string;
}

export const FOOD_SEED: FoodSeedEntry[] = [
  // ═══════════════════════════════════════════════
  // PROTEINS — Meat & Poultry
  // ═══════════════════════════════════════════════
  { name: 'Chicken breast, grilled', name_el: 'Στήθος κοτόπουλο ψητό', name_es: 'Pechuga de pollo a la plancha', calories_per_100g: 165, protein_per_100g: 31, carbs_per_100g: 0, fat_per_100g: 3.6, fiber_per_100g: 0, default_serving_grams: 175, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 175 }, { name: 'palm', grams: 120 }], category: 'protein' },
  { name: 'Chicken thigh, grilled', name_el: 'Μπούτι κοτόπουλο ψητό', name_es: 'Muslo de pollo a la plancha', calories_per_100g: 209, protein_per_100g: 26, carbs_per_100g: 0, fat_per_100g: 11, fiber_per_100g: 0, default_serving_grams: 130, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 130 }], category: 'protein' },
  { name: 'Ground beef, cooked', name_el: 'Κιμάς μοσχαρίσιος μαγειρεμένος', name_es: 'Carne molida cocida', calories_per_100g: 250, protein_per_100g: 26, carbs_per_100g: 0, fat_per_100g: 15, fiber_per_100g: 0, default_serving_grams: 100, default_serving_unit: '100g', common_units: [{ name: 'tbsp', grams: 15 }], category: 'protein' },
  { name: 'Beef patty, grilled', name_el: 'Μπιφτέκι μοσχαρίσιο ψητό', name_es: 'Hamburguesa de res', calories_per_100g: 250, protein_per_100g: 26, carbs_per_100g: 0, fat_per_100g: 15, fiber_per_100g: 0, default_serving_grams: 100, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 100 }], category: 'protein' },
  { name: 'Steak, grilled', name_el: 'Μπριζόλα ψητή', name_es: 'Bistec a la plancha', calories_per_100g: 271, protein_per_100g: 26, carbs_per_100g: 0, fat_per_100g: 18, fiber_per_100g: 0, default_serving_grams: 200, default_serving_unit: 'piece', common_units: [{ name: 'palm', grams: 120 }, { name: 'piece', grams: 200 }], category: 'protein' },
  { name: 'Pork loin, grilled', name_el: 'Χοιρινό φιλέτο ψητό', name_es: 'Lomo de cerdo a la plancha', calories_per_100g: 196, protein_per_100g: 27, carbs_per_100g: 0, fat_per_100g: 9, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 150 }], category: 'protein' },
  { name: 'Pork chop, grilled', name_el: 'Χοιρινή μπριζόλα ψητή', name_es: 'Chuleta de cerdo a la plancha', calories_per_100g: 231, protein_per_100g: 25, carbs_per_100g: 0, fat_per_100g: 14, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 150 }], category: 'protein' },
  { name: 'Turkey breast, cooked', name_el: 'Στήθος γαλοπούλας', name_es: 'Pechuga de pavo', calories_per_100g: 135, protein_per_100g: 30, carbs_per_100g: 0, fat_per_100g: 1, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'slice', grams: 30 }], category: 'protein' },
  { name: 'Lamb chop, grilled', name_el: 'Αρνίσια μπριζόλα ψητή', name_es: 'Chuleta de cordero', calories_per_100g: 282, protein_per_100g: 25, carbs_per_100g: 0, fat_per_100g: 20, fiber_per_100g: 0, default_serving_grams: 120, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 120 }], category: 'protein' },
  { name: 'Chicken souvlaki', name_el: 'Καλαμάκι κοτόπουλο', name_es: 'Souvlaki de pollo', calories_per_100g: 160, protein_per_100g: 21, carbs_per_100g: 2, fat_per_100g: 7, fiber_per_100g: 0, default_serving_grams: 80, default_serving_unit: 'skewer', common_units: [{ name: 'skewer', grams: 80 }], category: 'protein' },
  { name: 'Pork souvlaki', name_el: 'Καλαμάκι χοιρινό', name_es: 'Souvlaki de cerdo', calories_per_100g: 190, protein_per_100g: 20, carbs_per_100g: 2, fat_per_100g: 11, fiber_per_100g: 0, default_serving_grams: 80, default_serving_unit: 'skewer', common_units: [{ name: 'skewer', grams: 80 }], category: 'protein' },

  // ═══════════════════════════════════════════════
  // PROTEINS — Seafood
  // ═══════════════════════════════════════════════
  { name: 'Salmon, grilled', name_el: 'Σολομός ψητός', name_es: 'Salmón a la plancha', calories_per_100g: 208, protein_per_100g: 20, carbs_per_100g: 0, fat_per_100g: 13, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 150 }, { name: 'palm', grams: 120 }], category: 'protein' },
  { name: 'Smoked salmon', name_el: 'Σολομός καπνιστός', name_es: 'Salmón ahumado', calories_per_100g: 117, protein_per_100g: 18, carbs_per_100g: 0, fat_per_100g: 4.3, fiber_per_100g: 0, default_serving_grams: 60, default_serving_unit: 'serving', common_units: [{ name: 'palm', grams: 120 }, { name: 'slice', grams: 30 }], category: 'protein' },
  { name: 'Tuna, canned in water', name_el: 'Τόνος κονσέρβα', name_es: 'Atún en lata', calories_per_100g: 116, protein_per_100g: 26, carbs_per_100g: 0, fat_per_100g: 0.8, fiber_per_100g: 0, default_serving_grams: 100, default_serving_unit: 'can', common_units: [{ name: 'can', grams: 100 }], category: 'protein' },
  { name: 'Shrimp, cooked', name_el: 'Γαρίδες μαγειρεμένες', name_es: 'Camarones cocidos', calories_per_100g: 99, protein_per_100g: 24, carbs_per_100g: 0.2, fat_per_100g: 0.3, fiber_per_100g: 0, default_serving_grams: 100, default_serving_unit: '100g', common_units: [], category: 'protein' },
  { name: 'Cod, baked', name_el: 'Μπακαλιάρος ψητός', name_es: 'Bacalao al horno', calories_per_100g: 105, protein_per_100g: 23, carbs_per_100g: 0, fat_per_100g: 0.9, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 150 }], category: 'protein' },
  { name: 'Sea bass, grilled', name_el: 'Λαβράκι ψητό', name_es: 'Lubina a la plancha', calories_per_100g: 124, protein_per_100g: 24, carbs_per_100g: 0, fat_per_100g: 2.6, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 150 }], category: 'protein' },
  { name: 'Grilled octopus', name_el: 'Χταπόδι ψητό', name_es: 'Pulpo a la parrilla', calories_per_100g: 164, protein_per_100g: 30, carbs_per_100g: 4, fat_per_100g: 2, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 150 }], category: 'protein' },
  { name: 'Sardines, canned', name_el: 'Σαρδέλες κονσέρβα', name_es: 'Sardinas en lata', calories_per_100g: 208, protein_per_100g: 25, carbs_per_100g: 0, fat_per_100g: 11, fiber_per_100g: 0, default_serving_grams: 92, default_serving_unit: 'can', common_units: [{ name: 'can', grams: 92 }], category: 'protein' },

  // ═══════════════════════════════════════════════
  // PROTEINS — Eggs & Plant
  // ═══════════════════════════════════════════════
  { name: 'Egg, whole', name_el: 'Αυγό', name_es: 'Huevo', calories_per_100g: 143, protein_per_100g: 12.6, carbs_per_100g: 0.7, fat_per_100g: 9.5, fiber_per_100g: 0, default_serving_grams: 50, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 50 }, { name: 'large', grams: 56 }], category: 'protein' },
  { name: 'Egg, boiled', name_el: 'Αυγό βραστό', name_es: 'Huevo cocido', calories_per_100g: 155, protein_per_100g: 13, carbs_per_100g: 1.1, fat_per_100g: 11, fiber_per_100g: 0, default_serving_grams: 50, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 50 }], category: 'protein' },
  { name: 'Egg white', name_el: 'Ασπράδι αυγού', name_es: 'Clara de huevo', calories_per_100g: 52, protein_per_100g: 10.9, carbs_per_100g: 0.7, fat_per_100g: 0.2, fiber_per_100g: 0, default_serving_grams: 33, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 33 }], category: 'protein' },
  { name: 'Tofu, firm', name_el: 'Τόφου', name_es: 'Tofu firme', calories_per_100g: 144, protein_per_100g: 17, carbs_per_100g: 3, fat_per_100g: 9, fiber_per_100g: 2, default_serving_grams: 125, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 125 }], category: 'protein' },
  { name: 'Protein powder (whey)', name_el: 'Πρωτεΐνη σκόνη', name_es: 'Proteína en polvo', calories_per_100g: 380, protein_per_100g: 75, carbs_per_100g: 10, fat_per_100g: 5, fiber_per_100g: 0, default_serving_grams: 30, default_serving_unit: 'scoop', common_units: [{ name: 'scoop', grams: 30 }, { name: 'half_scoop', grams: 15 }], category: 'protein' },
  { name: 'Protein bar', name_el: 'Μπάρα πρωτεΐνης', name_es: 'Barra de proteína', calories_per_100g: 350, protein_per_100g: 27, carbs_per_100g: 35, fat_per_100g: 12, fiber_per_100g: 5, default_serving_grams: 55, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 55 }], category: 'protein' },

  // ═══════════════════════════════════════════════
  // DAIRY
  // ═══════════════════════════════════════════════
  { name: 'Greek yogurt 2%', name_el: 'Γιαούρτι 2%', name_es: 'Yogur griego 2%', calories_per_100g: 73, protein_per_100g: 10, carbs_per_100g: 3.6, fat_per_100g: 2, fiber_per_100g: 0, default_serving_grams: 170, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 170 }, { name: 'cup', grams: 245 }], category: 'dairy' },
  { name: 'Greek yogurt, full fat', name_el: 'Γιαούρτι πλήρες', name_es: 'Yogur griego entero', calories_per_100g: 97, protein_per_100g: 9, carbs_per_100g: 3.6, fat_per_100g: 5, fiber_per_100g: 0, default_serving_grams: 170, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 170 }], category: 'dairy' },
  { name: 'Feta cheese', name_el: 'Φέτα τυρί', name_es: 'Queso feta', calories_per_100g: 264, protein_per_100g: 14, carbs_per_100g: 4, fat_per_100g: 21, fiber_per_100g: 0, default_serving_grams: 30, default_serving_unit: 'slice', common_units: [{ name: 'slice', grams: 20 }, { name: '60g', grams: 60 }], category: 'dairy' },
  { name: 'Feta light', name_el: 'Φέτα light', name_es: 'Queso feta light', calories_per_100g: 180, protein_per_100g: 18, carbs_per_100g: 4, fat_per_100g: 10, fiber_per_100g: 0, default_serving_grams: 60, default_serving_unit: '60g', common_units: [{ name: '60g', grams: 60 }, { name: 'slice', grams: 20 }], category: 'dairy' },
  { name: 'Cottage cheese', name_el: 'Cottage', name_es: 'Requesón', calories_per_100g: 98, protein_per_100g: 11, carbs_per_100g: 3.4, fat_per_100g: 4.3, fiber_per_100g: 0, default_serving_grams: 113, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 113 }, { name: 'half', grams: 57 }], category: 'dairy' },
  { name: 'Halloumi cheese', name_el: 'Χαλούμι', name_es: 'Queso halloumi', calories_per_100g: 320, protein_per_100g: 22, carbs_per_100g: 3, fat_per_100g: 25, fiber_per_100g: 0, default_serving_grams: 30, default_serving_unit: 'slice', common_units: [{ name: 'slice', grams: 30 }], category: 'dairy' },
  { name: 'Mozzarella', name_el: 'Μοτσαρέλα', name_es: 'Mozzarella', calories_per_100g: 280, protein_per_100g: 28, carbs_per_100g: 3.1, fat_per_100g: 17, fiber_per_100g: 0, default_serving_grams: 30, default_serving_unit: 'slice', common_units: [{ name: 'slice', grams: 30 }, { name: 'ball', grams: 125 }], category: 'dairy' },
  { name: 'Parmesan cheese', name_el: 'Παρμεζάνα', name_es: 'Queso parmesano', calories_per_100g: 431, protein_per_100g: 38, carbs_per_100g: 4, fat_per_100g: 29, fiber_per_100g: 0, default_serving_grams: 10, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 10 }], category: 'dairy' },
  { name: 'Cheese slices', name_el: 'Φέτες τυρί', name_es: 'Lonchas de queso', calories_per_100g: 330, protein_per_100g: 22, carbs_per_100g: 2, fat_per_100g: 26, fiber_per_100g: 0, default_serving_grams: 20, default_serving_unit: 'slice', common_units: [{ name: 'slice', grams: 20 }], category: 'dairy' },
  { name: 'Philadelphia cream cheese', name_el: 'Φιλαδέλφεια', name_es: 'Queso crema Philadelphia', calories_per_100g: 342, protein_per_100g: 6, carbs_per_100g: 4, fat_per_100g: 34, fiber_per_100g: 0, default_serving_grams: 15, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 15 }], category: 'dairy' },
  { name: 'Milk, semi-skimmed', name_el: 'Γάλα 1.5%', name_es: 'Leche semidesnatada', calories_per_100g: 42, protein_per_100g: 3.4, carbs_per_100g: 5, fat_per_100g: 1, fiber_per_100g: 0, default_serving_grams: 250, default_serving_unit: 'glass', common_units: [{ name: 'glass', grams: 250 }, { name: 'half_glass', grams: 125 }], category: 'dairy' },
  { name: 'Frozen yogurt', name_el: 'Παγωτό γιαούρτι', name_es: 'Yogur helado', calories_per_100g: 127, protein_per_100g: 3, carbs_per_100g: 22, fat_per_100g: 3, fiber_per_100g: 0, default_serving_grams: 70, default_serving_unit: 'ball', common_units: [{ name: 'ball', grams: 70 }], category: 'dairy' },

  // ═══════════════════════════════════════════════
  // CARBS — Grains & Bread
  // ═══════════════════════════════════════════════
  { name: 'White rice, cooked', name_el: 'Ρύζι λευκό μαγειρεμένο', name_es: 'Arroz blanco cocido', calories_per_100g: 130, protein_per_100g: 2.7, carbs_per_100g: 28, fat_per_100g: 0.3, fiber_per_100g: 0.4, default_serving_grams: 100, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 185 }, { name: 'φλ', grams: 100 }], category: 'carb' },
  { name: 'Brown rice, cooked', name_el: 'Καστανό ρύζι μαγειρεμένο', name_es: 'Arroz integral cocido', calories_per_100g: 123, protein_per_100g: 2.7, carbs_per_100g: 26, fat_per_100g: 1, fiber_per_100g: 1.6, default_serving_grams: 100, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 185 }, { name: 'φλ', grams: 100 }], category: 'carb' },
  { name: 'Quinoa, cooked', name_el: 'Κινόα μαγειρεμένη', name_es: 'Quinoa cocida', calories_per_100g: 120, protein_per_100g: 4.4, carbs_per_100g: 21, fat_per_100g: 1.9, fiber_per_100g: 2.8, default_serving_grams: 100, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 185 }, { name: 'φλ', grams: 100 }], category: 'carb' },
  { name: 'Pasta, cooked', name_el: 'Μακαρόνια μαγειρεμένα', name_es: 'Pasta cocida', calories_per_100g: 131, protein_per_100g: 5, carbs_per_100g: 25, fat_per_100g: 1.1, fiber_per_100g: 1.8, default_serving_grams: 140, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 140 }], category: 'carb' },
  { name: 'Whole wheat bread', name_el: 'Ψωμί ολικής', name_es: 'Pan integral', calories_per_100g: 247, protein_per_100g: 13, carbs_per_100g: 41, fat_per_100g: 3.4, fiber_per_100g: 7, default_serving_grams: 30, default_serving_unit: 'slice', common_units: [{ name: 'slice', grams: 30 }], category: 'carb' },
  { name: 'White bread', name_el: 'Ψωμί λευκό', name_es: 'Pan blanco', calories_per_100g: 265, protein_per_100g: 9, carbs_per_100g: 49, fat_per_100g: 3.2, fiber_per_100g: 2.7, default_serving_grams: 30, default_serving_unit: 'slice', common_units: [{ name: 'slice', grams: 30 }], category: 'carb' },
  { name: 'Toast (whole wheat)', name_el: 'Τοστ ολικής', name_es: 'Tostada integral', calories_per_100g: 247, protein_per_100g: 13, carbs_per_100g: 41, fat_per_100g: 3.4, fiber_per_100g: 7, default_serving_grams: 60, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 60 }], category: 'carb' },
  { name: 'Oats', name_el: 'Βρώμη', name_es: 'Avena', calories_per_100g: 389, protein_per_100g: 17, carbs_per_100g: 66, fat_per_100g: 7, fiber_per_100g: 11, default_serving_grams: 40, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 40 }], category: 'carb' },
  { name: 'Oatmeal, cooked', name_el: 'Χυλός βρώμης', name_es: 'Avena cocida', calories_per_100g: 71, protein_per_100g: 2.5, carbs_per_100g: 12, fat_per_100g: 1.5, fiber_per_100g: 2, default_serving_grams: 240, default_serving_unit: 'bowl', common_units: [{ name: 'bowl', grams: 240 }], category: 'carb' },
  { name: 'Pita bread', name_el: 'Πίτα', name_es: 'Pan pita', calories_per_100g: 275, protein_per_100g: 9.1, carbs_per_100g: 55, fat_per_100g: 1.2, fiber_per_100g: 2.2, default_serving_grams: 60, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 60 }], category: 'carb' },
  { name: 'Tortilla / Wrap', name_el: 'Τυλιχτό / Πίτα', name_es: 'Tortilla / Wrap', calories_per_100g: 310, protein_per_100g: 8, carbs_per_100g: 50, fat_per_100g: 8, fiber_per_100g: 3, default_serving_grams: 65, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 65 }], category: 'carb' },
  { name: 'Rusks, whole wheat', name_el: 'Παξιμάδια ολικής', name_es: 'Bizcocho integral', calories_per_100g: 380, protein_per_100g: 11, carbs_per_100g: 70, fat_per_100g: 5, fiber_per_100g: 6, default_serving_grams: 40, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 40 }], category: 'carb' },
  { name: 'Corn tortilla', name_el: 'Τορτίγια καλαμποκιού', name_es: 'Tortilla de maíz', calories_per_100g: 218, protein_per_100g: 6, carbs_per_100g: 45, fat_per_100g: 3, fiber_per_100g: 6, default_serving_grams: 26, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 26 }], category: 'carb' },
  { name: 'Couscous, cooked', name_el: 'Κουσκούς μαγειρεμένο', name_es: 'Cuscús cocido', calories_per_100g: 112, protein_per_100g: 3.8, carbs_per_100g: 23, fat_per_100g: 0.2, fiber_per_100g: 1.4, default_serving_grams: 160, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 160 }], category: 'carb' },

  // ═══════════════════════════════════════════════
  // CARBS — Potatoes & Starchy
  // ═══════════════════════════════════════════════
  { name: 'Potato, boiled', name_el: 'Πατάτα βραστή', name_es: 'Papa cocida', calories_per_100g: 87, protein_per_100g: 1.9, carbs_per_100g: 20, fat_per_100g: 0.1, fiber_per_100g: 1.8, default_serving_grams: 150, default_serving_unit: 'medium', common_units: [{ name: 'medium', grams: 150 }, { name: 'fistful', grams: 75 }], category: 'carb' },
  { name: 'Potato, roasted', name_el: 'Πατάτα ψητή', name_es: 'Papa asada', calories_per_100g: 93, protein_per_100g: 2.5, carbs_per_100g: 21, fat_per_100g: 0.1, fiber_per_100g: 2.2, default_serving_grams: 150, default_serving_unit: 'medium', common_units: [{ name: 'medium', grams: 150 }, { name: 'fistful', grams: 75 }], category: 'carb' },
  { name: 'Sweet potato, baked', name_el: 'Γλυκοπατάτα ψητή', name_es: 'Camote al horno', calories_per_100g: 90, protein_per_100g: 2, carbs_per_100g: 21, fat_per_100g: 0.1, fiber_per_100g: 3.3, default_serving_grams: 130, default_serving_unit: 'medium', common_units: [{ name: 'medium', grams: 130 }], category: 'carb' },
  { name: 'French fries', name_el: 'Πατάτες τηγανητές', name_es: 'Papas fritas', calories_per_100g: 312, protein_per_100g: 3.4, carbs_per_100g: 41, fat_per_100g: 15, fiber_per_100g: 3.8, default_serving_grams: 100, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 100 }], category: 'carb' },

  // ═══════════════════════════════════════════════
  // FATS & NUTS
  // ═══════════════════════════════════════════════
  { name: 'Olive oil', name_el: 'Ελαιόλαδο', name_es: 'Aceite de oliva', calories_per_100g: 884, protein_per_100g: 0, carbs_per_100g: 0, fat_per_100g: 100, fiber_per_100g: 0, default_serving_grams: 14, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 14 }, { name: 'tsp', grams: 5 }], category: 'fat' },
  { name: 'Butter', name_el: 'Βούτυρο', name_es: 'Mantequilla', calories_per_100g: 717, protein_per_100g: 0.9, carbs_per_100g: 0.1, fat_per_100g: 81, fiber_per_100g: 0, default_serving_grams: 14, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 14 }, { name: 'tsp', grams: 5 }], category: 'fat' },
  { name: 'Peanut butter', name_el: 'Φυστικοβούτυρο', name_es: 'Mantequilla de maní', calories_per_100g: 588, protein_per_100g: 25, carbs_per_100g: 20, fat_per_100g: 50, fiber_per_100g: 6, default_serving_grams: 15, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 15 }, { name: 'tsp', grams: 5 }], category: 'fat' },
  { name: 'Avocado', name_el: 'Αβοκάντο', name_es: 'Aguacate', calories_per_100g: 160, protein_per_100g: 2, carbs_per_100g: 8.5, fat_per_100g: 15, fiber_per_100g: 7, default_serving_grams: 75, default_serving_unit: 'half', common_units: [{ name: 'half', grams: 75 }, { name: 'whole', grams: 150 }], category: 'fat' },
  { name: 'Almonds', name_el: 'Αμύγδαλα', name_es: 'Almendras', calories_per_100g: 579, protein_per_100g: 21, carbs_per_100g: 22, fat_per_100g: 50, fiber_per_100g: 12, default_serving_grams: 30, default_serving_unit: 'handful', common_units: [{ name: 'handful', grams: 30 }], category: 'fat' },
  { name: 'Walnuts', name_el: 'Καρύδια', name_es: 'Nueces', calories_per_100g: 654, protein_per_100g: 15, carbs_per_100g: 14, fat_per_100g: 65, fiber_per_100g: 7, default_serving_grams: 30, default_serving_unit: 'handful', common_units: [{ name: 'handful', grams: 30 }], category: 'fat' },
  { name: 'Mixed nuts', name_el: 'Ξηροί καρποί', name_es: 'Frutos secos', calories_per_100g: 607, protein_per_100g: 20, carbs_per_100g: 21, fat_per_100g: 54, fiber_per_100g: 7, default_serving_grams: 30, default_serving_unit: 'handful', common_units: [{ name: 'handful', grams: 30 }], category: 'fat' },
  { name: 'Dried fruits', name_el: 'Αποξηραμένα φρούτα', name_es: 'Frutas secas', calories_per_100g: 359, protein_per_100g: 3, carbs_per_100g: 83, fat_per_100g: 0.5, fiber_per_100g: 7, default_serving_grams: 30, default_serving_unit: 'handful', common_units: [{ name: 'handful', grams: 30 }], category: 'fat' },
  { name: 'Tahini', name_el: 'Ταχίνι', name_es: 'Tahini', calories_per_100g: 595, protein_per_100g: 17, carbs_per_100g: 21, fat_per_100g: 54, fiber_per_100g: 10, default_serving_grams: 15, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 15 }], category: 'fat' },
  { name: 'Coconut oil', name_el: 'Λάδι καρύδας', name_es: 'Aceite de coco', calories_per_100g: 862, protein_per_100g: 0, carbs_per_100g: 0, fat_per_100g: 100, fiber_per_100g: 0, default_serving_grams: 14, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 14 }], category: 'fat' },

  // ═══════════════════════════════════════════════
  // FRUITS
  // ═══════════════════════════════════════════════
  { name: 'Banana', name_el: 'Μπανάνα', name_es: 'Plátano', calories_per_100g: 89, protein_per_100g: 1.1, carbs_per_100g: 23, fat_per_100g: 0.3, fiber_per_100g: 2.6, default_serving_grams: 120, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 120 }], category: 'fruit' },
  { name: 'Apple', name_el: 'Μήλο', name_es: 'Manzana', calories_per_100g: 52, protein_per_100g: 0.3, carbs_per_100g: 14, fat_per_100g: 0.2, fiber_per_100g: 2.4, default_serving_grams: 180, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 180 }], category: 'fruit' },
  { name: 'Orange', name_el: 'Πορτοκάλι', name_es: 'Naranja', calories_per_100g: 47, protein_per_100g: 0.9, carbs_per_100g: 12, fat_per_100g: 0.1, fiber_per_100g: 2.4, default_serving_grams: 130, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 130 }], category: 'fruit' },
  { name: 'Strawberries', name_el: 'Φράουλες', name_es: 'Fresas', calories_per_100g: 32, protein_per_100g: 0.7, carbs_per_100g: 7.7, fat_per_100g: 0.3, fiber_per_100g: 2, default_serving_grams: 150, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 150 }], category: 'fruit' },
  { name: 'Blueberries', name_el: 'Μύρτιλα', name_es: 'Arándanos', calories_per_100g: 57, protein_per_100g: 0.7, carbs_per_100g: 14, fat_per_100g: 0.3, fiber_per_100g: 2.4, default_serving_grams: 150, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 150 }], category: 'fruit' },
  { name: 'Grapes', name_el: 'Σταφύλια', name_es: 'Uvas', calories_per_100g: 69, protein_per_100g: 0.7, carbs_per_100g: 18, fat_per_100g: 0.2, fiber_per_100g: 0.9, default_serving_grams: 150, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 150 }], category: 'fruit' },
  { name: 'Watermelon', name_el: 'Καρπούζι', name_es: 'Sandía', calories_per_100g: 30, protein_per_100g: 0.6, carbs_per_100g: 8, fat_per_100g: 0.2, fiber_per_100g: 0.4, default_serving_grams: 280, default_serving_unit: 'slice', common_units: [{ name: 'slice', grams: 280 }], category: 'fruit' },
  { name: 'Peach', name_el: 'Ροδάκινο', name_es: 'Durazno', calories_per_100g: 39, protein_per_100g: 0.9, carbs_per_100g: 10, fat_per_100g: 0.3, fiber_per_100g: 1.5, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 150 }], category: 'fruit' },
  { name: 'Pear', name_el: 'Αχλάδι', name_es: 'Pera', calories_per_100g: 57, protein_per_100g: 0.4, carbs_per_100g: 15, fat_per_100g: 0.1, fiber_per_100g: 3.1, default_serving_grams: 180, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 180 }], category: 'fruit' },
  { name: 'Kiwi', name_el: 'Ακτινίδιο', name_es: 'Kiwi', calories_per_100g: 61, protein_per_100g: 1.1, carbs_per_100g: 15, fat_per_100g: 0.5, fiber_per_100g: 3, default_serving_grams: 75, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 75 }], category: 'fruit' },
  { name: 'Mango', name_el: 'Μάνγκο', name_es: 'Mango', calories_per_100g: 60, protein_per_100g: 0.8, carbs_per_100g: 15, fat_per_100g: 0.4, fiber_per_100g: 1.6, default_serving_grams: 200, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 200 }], category: 'fruit' },
  { name: 'Pineapple', name_el: 'Ανανάς', name_es: 'Piña', calories_per_100g: 50, protein_per_100g: 0.5, carbs_per_100g: 13, fat_per_100g: 0.1, fiber_per_100g: 1.4, default_serving_grams: 165, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 165 }], category: 'fruit' },

  // ═══════════════════════════════════════════════
  // VEGETABLES
  // ═══════════════════════════════════════════════
  { name: 'Salad / mixed greens', name_el: 'Σαλάτα / λαχανικά', name_es: 'Ensalada / verduras', calories_per_100g: 20, protein_per_100g: 1.5, carbs_per_100g: 3.5, fat_per_100g: 0.2, fiber_per_100g: 2, default_serving_grams: 200, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 200 }], category: 'vegetable' },
  { name: 'Roasted vegetables', name_el: 'Ψητά λαχανικά', name_es: 'Verduras asadas', calories_per_100g: 45, protein_per_100g: 1.5, carbs_per_100g: 7, fat_per_100g: 1.5, fiber_per_100g: 2.5, default_serving_grams: 200, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 200 }], category: 'vegetable' },
  { name: 'Spinach, raw', name_el: 'Σπανάκι', name_es: 'Espinaca', calories_per_100g: 23, protein_per_100g: 2.9, carbs_per_100g: 3.6, fat_per_100g: 0.4, fiber_per_100g: 2.2, default_serving_grams: 30, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 30 }], category: 'vegetable' },
  { name: 'Broccoli, cooked', name_el: 'Μπρόκολο', name_es: 'Brócoli cocido', calories_per_100g: 35, protein_per_100g: 2.4, carbs_per_100g: 7, fat_per_100g: 0.4, fiber_per_100g: 3.3, default_serving_grams: 90, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 90 }], category: 'vegetable' },
  { name: 'Tomato', name_el: 'Ντομάτα', name_es: 'Tomate', calories_per_100g: 18, protein_per_100g: 0.9, carbs_per_100g: 3.9, fat_per_100g: 0.2, fiber_per_100g: 1.2, default_serving_grams: 120, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 120 }], category: 'vegetable' },
  { name: 'Cucumber', name_el: 'Αγγούρι', name_es: 'Pepino', calories_per_100g: 15, protein_per_100g: 0.7, carbs_per_100g: 3.6, fat_per_100g: 0.1, fiber_per_100g: 0.5, default_serving_grams: 150, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 150 }], category: 'vegetable' },
  { name: 'Bell pepper', name_el: 'Πιπεριά', name_es: 'Pimiento', calories_per_100g: 31, protein_per_100g: 1, carbs_per_100g: 6, fat_per_100g: 0.3, fiber_per_100g: 2.1, default_serving_grams: 120, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 120 }], category: 'vegetable' },
  { name: 'Zucchini', name_el: 'Κολοκυθάκι', name_es: 'Calabacín', calories_per_100g: 17, protein_per_100g: 1.2, carbs_per_100g: 3.1, fat_per_100g: 0.3, fiber_per_100g: 1, default_serving_grams: 120, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 120 }], category: 'vegetable' },
  { name: 'Onion', name_el: 'Κρεμμύδι', name_es: 'Cebolla', calories_per_100g: 40, protein_per_100g: 1.1, carbs_per_100g: 9.3, fat_per_100g: 0.1, fiber_per_100g: 1.7, default_serving_grams: 110, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 110 }], category: 'vegetable' },
  { name: 'Carrot', name_el: 'Καρότο', name_es: 'Zanahoria', calories_per_100g: 41, protein_per_100g: 0.9, carbs_per_100g: 10, fat_per_100g: 0.2, fiber_per_100g: 2.8, default_serving_grams: 60, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 60 }], category: 'vegetable' },
  { name: 'Mushrooms', name_el: 'Μανιτάρια', name_es: 'Champiñones', calories_per_100g: 22, protein_per_100g: 3.1, carbs_per_100g: 3.3, fat_per_100g: 0.3, fiber_per_100g: 1, default_serving_grams: 70, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 70 }], category: 'vegetable' },
  { name: 'Eggplant', name_el: 'Μελιτζάνα', name_es: 'Berenjena', calories_per_100g: 25, protein_per_100g: 1, carbs_per_100g: 6, fat_per_100g: 0.2, fiber_per_100g: 3, default_serving_grams: 82, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 82 }], category: 'vegetable' },
  { name: 'Lettuce', name_el: 'Μαρούλι', name_es: 'Lechuga', calories_per_100g: 15, protein_per_100g: 1.4, carbs_per_100g: 2.9, fat_per_100g: 0.2, fiber_per_100g: 1.3, default_serving_grams: 50, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 50 }], category: 'vegetable' },

  // ═══════════════════════════════════════════════
  // LEGUMES
  // ═══════════════════════════════════════════════
  { name: 'Green beans (fasolakia)', name_el: 'Φασολάκια', name_es: 'Judías verdes', calories_per_100g: 35, protein_per_100g: 1.8, carbs_per_100g: 7, fat_per_100g: 0.1, fiber_per_100g: 3.4, default_serving_grams: 125, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 125 }], category: 'legume' },
  { name: 'Peas, cooked', name_el: 'Αρακάς', name_es: 'Guisantes cocidos', calories_per_100g: 81, protein_per_100g: 5.4, carbs_per_100g: 14, fat_per_100g: 0.4, fiber_per_100g: 5, default_serving_grams: 160, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 160 }], category: 'legume' },
  { name: 'Lentils, cooked', name_el: 'Φακές μαγειρεμένες', name_es: 'Lentejas cocidas', calories_per_100g: 116, protein_per_100g: 9, carbs_per_100g: 20, fat_per_100g: 0.4, fiber_per_100g: 8, default_serving_grams: 200, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 200 }], category: 'legume' },
  { name: 'Chickpeas, cooked', name_el: 'Ρεβίθια μαγειρεμένα', name_es: 'Garbanzos cocidos', calories_per_100g: 164, protein_per_100g: 8.9, carbs_per_100g: 27, fat_per_100g: 2.6, fiber_per_100g: 8, default_serving_grams: 160, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 160 }], category: 'legume' },
  { name: 'White beans, cooked', name_el: 'Φασόλια λευκά μαγειρεμένα', name_es: 'Alubias blancas cocidas', calories_per_100g: 139, protein_per_100g: 9.7, carbs_per_100g: 25, fat_per_100g: 0.5, fiber_per_100g: 6, default_serving_grams: 180, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 180 }], category: 'legume' },
  { name: 'Hummus', name_el: 'Χούμους', name_es: 'Hummus', calories_per_100g: 166, protein_per_100g: 8, carbs_per_100g: 14, fat_per_100g: 10, fiber_per_100g: 6, default_serving_grams: 50, default_serving_unit: 'serving', common_units: [{ name: 'tbsp', grams: 15 }, { name: 'serving', grams: 50 }], category: 'legume' },
  { name: 'Bean soup (fasolada)', name_el: 'Φασολάδα', name_es: 'Sopa de frijoles', calories_per_100g: 88, protein_per_100g: 5, carbs_per_100g: 15, fat_per_100g: 1, fiber_per_100g: 4, default_serving_grams: 300, default_serving_unit: 'bowl', common_units: [{ name: 'bowl', grams: 300 }], category: 'legume' },

  // ═══════════════════════════════════════════════
  // GREEK DISHES
  // ═══════════════════════════════════════════════
  { name: 'Moussaka', name_el: 'Μουσακάς', name_es: 'Musaca', calories_per_100g: 140, protein_per_100g: 7, carbs_per_100g: 10, fat_per_100g: 8, fiber_per_100g: 1.5, default_serving_grams: 250, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 250 }], category: 'greek' },
  { name: 'Pastitsio', name_el: 'Παστίτσιο', name_es: 'Pastitsio', calories_per_100g: 152, protein_per_100g: 7, carbs_per_100g: 15, fat_per_100g: 7, fiber_per_100g: 1, default_serving_grams: 250, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 250 }], category: 'greek' },
  { name: 'Briam (roasted veg)', name_el: 'Μπριάμ', name_es: 'Verduras griegas asadas', calories_per_100g: 80, protein_per_100g: 1.5, carbs_per_100g: 10, fat_per_100g: 4, fiber_per_100g: 2.5, default_serving_grams: 250, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 250 }], category: 'greek' },
  { name: 'Spanakopita', name_el: 'Σπανακόπιτα', name_es: 'Spanakopita', calories_per_100g: 280, protein_per_100g: 8, carbs_per_100g: 25, fat_per_100g: 16, fiber_per_100g: 2, default_serving_grams: 100, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 100 }], category: 'greek' },
  { name: 'Tzatziki', name_el: 'Τζατζίκι', name_es: 'Tzatziki', calories_per_100g: 55, protein_per_100g: 3, carbs_per_100g: 4, fat_per_100g: 3, fiber_per_100g: 0, default_serving_grams: 50, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 50 }, { name: 'tbsp', grams: 15 }], category: 'greek' },
  { name: 'Dolmades', name_el: 'Ντολμαδάκια', name_es: 'Dolmades', calories_per_100g: 190, protein_per_100g: 4, carbs_per_100g: 20, fat_per_100g: 10, fiber_per_100g: 3, default_serving_grams: 100, default_serving_unit: 'serving', common_units: [{ name: 'piece', grams: 25 }], category: 'greek' },
  { name: 'Greek salad (Horiatiki)', name_el: 'Χωριάτικη σαλάτα', name_es: 'Ensalada griega', calories_per_100g: 78, protein_per_100g: 3, carbs_per_100g: 5, fat_per_100g: 5, fiber_per_100g: 1.5, default_serving_grams: 300, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 300 }], category: 'greek' },
  { name: 'Dakos salad', name_el: 'Σαλάτα Ντάκος', name_es: 'Ensalada Dakos', calories_per_100g: 150, protein_per_100g: 5, carbs_per_100g: 18, fat_per_100g: 6, fiber_per_100g: 2, default_serving_grams: 300, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 300 }], category: 'greek' },
  { name: 'Gyros (pork)', name_el: 'Γύρος χοιρινός', name_es: 'Gyros de cerdo', calories_per_100g: 208, protein_per_100g: 18, carbs_per_100g: 4, fat_per_100g: 13, fiber_per_100g: 0, default_serving_grams: 200, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 200 }], category: 'greek' },
  { name: 'Gemista (stuffed veg)', name_el: 'Γεμιστά', name_es: 'Verduras rellenas', calories_per_100g: 85, protein_per_100g: 3, carbs_per_100g: 12, fat_per_100g: 3, fiber_per_100g: 2, default_serving_grams: 200, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 200 }], category: 'greek' },
  { name: 'Saganaki (fried cheese)', name_el: 'Σαγανάκι', name_es: 'Saganaki', calories_per_100g: 340, protein_per_100g: 20, carbs_per_100g: 8, fat_per_100g: 26, fiber_per_100g: 0, default_serving_grams: 80, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 80 }], category: 'greek' },

  // ═══════════════════════════════════════════════
  // BEVERAGES
  // ═══════════════════════════════════════════════
  { name: 'Coffee, black', name_el: 'Καφές σκέτος', name_es: 'Café negro', calories_per_100g: 2, protein_per_100g: 0.3, carbs_per_100g: 0, fat_per_100g: 0, fiber_per_100g: 0, default_serving_grams: 240, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 240 }], category: 'beverage' },
  { name: 'Coffee with milk', name_el: 'Καφές με γάλα', name_es: 'Café con leche', calories_per_100g: 20, protein_per_100g: 1, carbs_per_100g: 2, fat_per_100g: 0.7, fiber_per_100g: 0, default_serving_grams: 240, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 240 }], category: 'beverage' },
  { name: 'Greek coffee', name_el: 'Ελληνικός καφές', name_es: 'Café griego', calories_per_100g: 2, protein_per_100g: 0.1, carbs_per_100g: 0, fat_per_100g: 0, fiber_per_100g: 0, default_serving_grams: 60, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 60 }], category: 'beverage' },
  { name: 'Orange juice', name_el: 'Χυμός πορτοκάλι', name_es: 'Jugo de naranja', calories_per_100g: 45, protein_per_100g: 0.7, carbs_per_100g: 10, fat_per_100g: 0.2, fiber_per_100g: 0.2, default_serving_grams: 250, default_serving_unit: 'glass', common_units: [{ name: 'glass', grams: 250 }], category: 'beverage' },
  { name: 'Tea', name_el: 'Τσάι', name_es: 'Té', calories_per_100g: 1, protein_per_100g: 0, carbs_per_100g: 0.3, fat_per_100g: 0, fiber_per_100g: 0, default_serving_grams: 240, default_serving_unit: 'cup', common_units: [{ name: 'cup', grams: 240 }], category: 'beverage' },

  // ═══════════════════════════════════════════════
  // CONDIMENTS & SAUCES
  // ═══════════════════════════════════════════════
  { name: 'Honey', name_el: 'Μέλι', name_es: 'Miel', calories_per_100g: 304, protein_per_100g: 0.3, carbs_per_100g: 82, fat_per_100g: 0, fiber_per_100g: 0, default_serving_grams: 7, default_serving_unit: 'tsp', common_units: [{ name: 'tsp', grams: 7 }, { name: 'tbsp', grams: 21 }], category: 'condiment' },
  { name: 'Pesto sauce', name_el: 'Πέστο', name_es: 'Pesto', calories_per_100g: 418, protein_per_100g: 6, carbs_per_100g: 6, fat_per_100g: 41, fiber_per_100g: 2, default_serving_grams: 15, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 15 }], category: 'condiment' },
  { name: 'Mustard', name_el: 'Μουστάρδα', name_es: 'Mostaza', calories_per_100g: 66, protein_per_100g: 4, carbs_per_100g: 6, fat_per_100g: 3, fiber_per_100g: 3, default_serving_grams: 5, default_serving_unit: 'tsp', common_units: [{ name: 'tsp', grams: 5 }], category: 'condiment' },
  { name: 'Ketchup', name_el: 'Κέτσαπ', name_es: 'Ketchup', calories_per_100g: 112, protein_per_100g: 1.7, carbs_per_100g: 26, fat_per_100g: 0.1, fiber_per_100g: 0.3, default_serving_grams: 17, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 17 }], category: 'condiment' },
  { name: 'Balsamic vinegar', name_el: 'Βαλσαμικό ξύδι', name_es: 'Vinagre balsámico', calories_per_100g: 88, protein_per_100g: 0.5, carbs_per_100g: 17, fat_per_100g: 0, fiber_per_100g: 0, default_serving_grams: 15, default_serving_unit: 'tbsp', common_units: [{ name: 'tbsp', grams: 15 }], category: 'condiment' },

  // ═══════════════════════════════════════════════
  // SNACKS & SWEETS
  // ═══════════════════════════════════════════════
  { name: 'Dark chocolate (health)', name_el: 'Σοκολάτα υγείας', name_es: 'Chocolate negro', calories_per_100g: 546, protein_per_100g: 5, carbs_per_100g: 60, fat_per_100g: 31, fiber_per_100g: 7, default_serving_grams: 20, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 20 }, { name: 'square', grams: 10 }], category: 'snack' },
  { name: 'Baklava', name_el: 'Μπακλαβάς', name_es: 'Baklava', calories_per_100g: 340, protein_per_100g: 5, carbs_per_100g: 40, fat_per_100g: 18, fiber_per_100g: 2, default_serving_grams: 80, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 80 }], category: 'greek' },
  { name: 'Loukoumades', name_el: 'Λουκουμάδες', name_es: 'Loukoumades', calories_per_100g: 290, protein_per_100g: 5, carbs_per_100g: 38, fat_per_100g: 13, fiber_per_100g: 1, default_serving_grams: 100, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 100 }], category: 'greek' },
  { name: 'Galaktoboureko', name_el: 'Γαλακτομπούρεκο', name_es: 'Galaktoboureko', calories_per_100g: 310, protein_per_100g: 6, carbs_per_100g: 40, fat_per_100g: 14, fiber_per_100g: 0, default_serving_grams: 120, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 120 }], category: 'greek' },
  { name: 'Rice cake', name_el: 'Ρυζογκοφρέτα', name_es: 'Torta de arroz', calories_per_100g: 387, protein_per_100g: 8, carbs_per_100g: 81, fat_per_100g: 3, fiber_per_100g: 4, default_serving_grams: 9, default_serving_unit: 'piece', common_units: [{ name: 'piece', grams: 9 }], category: 'snack' },

  // ═══════════════════════════════════════════════
  // OMELETTE / COMPOSITE (Kavdas plan items)
  // ═══════════════════════════════════════════════
  { name: 'Omelette (3 eggs, feta)', name_el: 'Ομελέτα (3 αυγά, φέτα)', name_es: 'Tortilla (3 huevos, feta)', calories_per_100g: 175, protein_per_100g: 13, carbs_per_100g: 1, fat_per_100g: 13, fiber_per_100g: 0, default_serving_grams: 200, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 200 }], category: 'protein' },
  { name: 'Scrambled eggs', name_el: 'Αυγά scrambled', name_es: 'Huevos revueltos', calories_per_100g: 149, protein_per_100g: 10, carbs_per_100g: 2, fat_per_100g: 11, fiber_per_100g: 0, default_serving_grams: 150, default_serving_unit: 'serving', common_units: [{ name: 'serving', grams: 150 }], category: 'protein' },
  { name: 'Smoothie (fruit + protein)', name_el: 'Smoothie (φρούτα + πρωτεΐνη)', name_es: 'Smoothie (fruta + proteína)', calories_per_100g: 65, protein_per_100g: 4, carbs_per_100g: 10, fat_per_100g: 1, fiber_per_100g: 1, default_serving_grams: 400, default_serving_unit: 'glass', common_units: [{ name: 'glass', grams: 400 }], category: 'beverage' },
];
