// @vitest-environment jsdom
import React from 'react';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {I18nProvider} from '@/lib/i18n';
import {PhotoFoodController} from '@/components/assistant/photo-food-state';
import {PhotoFoodPanel} from '@/components/assistant/PhotoFoodPanel';
import {FoodQuantityController,type FoodTransport} from '@/components/assistant/food-state';
import {FoodQuantityPanel} from '@/components/assistant/FoodQuantityPanel';
import type {PhotoFoodTransport} from '@/components/assistant/photo-food-client';
import type {PhotoFoodOperation} from '@/agents/coach-assistant/photo-food-actions';
const id=()=>crypto.randomUUID(),conversation=id(),attachment=id(),observation=id(),hash='a'.repeat(64);
function fixture(){const controller=new PhotoFoodController();let proposalId='';let saved:Awaited<ReturnType<PhotoFoodTransport>>;const transport=vi.fn<PhotoFoodTransport>(async op=>{
 if(op.operation==='photo.food.read')return {version:'coach-assistant.v2',storage:'offline_fixture',ok:true,snapshot:{observationId:observation,attachmentId:attachment,source:'offline_fixture',trust:'untrusted_image_data',reviewRequired:true,items:[{index:0,version:hash,foodName:'Fixture rice',estimatedGrams:100,estimatedCalories:130,confidence:.7,accuracyNote:'Estimate'}]}};
 if(op.operation==='photo.food.propose'){proposalId=id();return {version:'coach-assistant.v2',storage:'offline_fixture',ok:true,proposal:{id:proposalId,hash:'b'.repeat(64),action:'food.photo.create',resource:{kind:'food_entry',id:proposalId,version:hash},before:null,after:{...op.after,foodName:'Fixture rice',calories:195,proteinG:4,carbsG:42,fatG:.5,fiberG:.6,sugarG:0,confidence:.7,source:'photo_ai',nutrition:'estimated',portion:'explicit_user'},evidence:{observationId:observation,observationRevision:id(),attachmentId:attachment,imageDigest:'c'.repeat(64),itemIndex:0,source:'offline_fixture',trust:'untrusted_image_data'},precondition:hash,expiresAt:new Date(Date.now()+300000).toISOString(),reviewRequired:true}};
 }
 if(op.operation==='photo.food.apply'){saved={version:'coach-assistant.v2',storage:'isolated_database_fixture',evaluation:{mode:'isolated_authorized_fixture',observation:'offline_fixture',visionVerified:false,paidApiCalls:0},ok:true,receipt:{id:id(),actionId:op.actionId,proposalId,status:'applied',action:'food.photo.create',resourceVersion:'1',recordedAt:new Date().toISOString()},refresh:{entryId:proposalId,loggedDate:'2026-09-08',previousVersion:hash,version:'1',strategy:'refetch'}};return saved;}
 return saved;
 });return {controller,transport};}
afterEach(()=>cleanup());
it('labels the offline observation, writes only after confirmation and renders the canonical Food readback',async()=>{const {controller,transport}=fixture(),food=new FoodQuantityController();const foodTransport=vi.fn<FoodTransport>(async op=>{if(!('entryId' in op))throw new Error('invalid food operation');return {version:'coach-assistant.v2',storage:'database',ok:true,snapshot:{entryId:op.entryId,version:'1',loggedDate:'2026-09-08',foodName:'Fixture rice',foodId:null,source:'photo_ai',sourceId:observation,grams:150,quantity:150,calories:195,proteinG:4,carbsG:42,fatG:.5,fiberG:.6,sugarG:0}};});await controller.select(attachment,conversation,transport);function View(){const state=React.useSyncExternalStore(controller.subscribe,controller.snapshot),foodState=React.useSyncExternalStore(food.subscribe,food.snapshot);return <I18nProvider defaultLang="en"><PhotoFoodPanel controller={controller} state={state} transport={transport} onReceipt={entryId=>food.select(entryId,conversation,foodTransport)}/>{foodState.entryId&&<FoodQuantityPanel controller={food} state={foodState} transport={foodTransport}/>}</I18nProvider>}render(<View/>);expect(screen.getByText(/Offline test observation/)).toBeTruthy();fireEvent.change(screen.getByLabelText('Grams'),{target:{value:'150'}});fireEvent.click(screen.getByRole('button',{name:'Review food entry'}));await screen.findByRole('button',{name:'Confirm and save food'});expect(screen.getByRole('table').textContent).toContain('100150');expect(transport.mock.calls.filter(([op])=>op.operation==='photo.food.apply')).toHaveLength(0);fireEvent.click(screen.getByRole('button',{name:'Confirm and save food'}));await screen.findByText('Current entry · 150 g · 195 kcal');expect(controller.snapshot().refreshEntryId).toBeTruthy();expect(transport.mock.calls.map(([op])=>op.operation)).toEqual(['photo.food.read','photo.food.propose','photo.food.apply']);expect(foodTransport.mock.calls.map(([op])=>op.operation)).toEqual(['food.read']);});
it('cancels a read without accepting late data',async()=>{const controller=new PhotoFoodController();let resolve!:(value:Awaited<ReturnType<PhotoFoodTransport>>)=>void;const transport:PhotoFoodTransport=()=>new Promise(done=>{resolve=done;});const selecting=controller.select(attachment,conversation,transport);controller.cancel();resolve({version:'coach-assistant.v2',storage:'offline_fixture',ok:true,snapshot:{observationId:observation,attachmentId:attachment,source:'offline_fixture',trust:'untrusted_image_data',reviewRequired:true,items:[{index:0,version:hash,foodName:'Rice',estimatedGrams:100,estimatedCalories:100,confidence:.5,accuracyNote:''}]}});await selecting;expect(controller.snapshot().snapshot).toBeNull();});
it('recovers a lost apply with the same action id and never writes twice',async()=>{const {controller,transport}=fixture();await controller.select(attachment,conversation,transport);await controller.propose({loggedDate:'2026-09-08',mealType:'lunch',grams:150},transport);const actual=transport.getMockImplementation()!;transport.mockImplementation(async(op,signal)=>{const result=await actual(op,signal);if(op.operation==='photo.food.apply')throw Error('lost');return result;});await controller.apply(transport);expect(controller.snapshot().uncertain).toBe(true);await controller.check(transport);const apply=transport.mock.calls.find(([op])=>op.operation==='photo.food.apply')![0] as Extract<PhotoFoodOperation,{operation:'photo.food.apply'}>;const receipt=transport.mock.calls.find(([op])=>op.operation==='photo.food.receipt')![0] as Extract<PhotoFoodOperation,{operation:'photo.food.receipt'}>;expect(receipt.actionId).toBe(apply.actionId);expect(transport.mock.calls.filter(([op])=>op.operation==='photo.food.apply')).toHaveLength(1);expect(controller.snapshot().receipt?.status).toBe('applied');});
it('invalidates an unconfirmed proposal when the conversation changes',async()=>{const {controller,transport}=fixture();await controller.select(attachment,conversation,transport);await controller.propose({loggedDate:'2026-09-08',mealType:'lunch',grams:150},transport);expect(controller.snapshot().proposal).toBeTruthy();controller.moveConversation(id());expect(controller.snapshot()).toMatchObject({attachmentId:null,snapshot:null,proposal:null,receipt:null,uncertain:false});await controller.apply(transport);await controller.check(transport);expect(transport.mock.calls.filter(([op])=>op.operation==='photo.food.apply'||op.operation==='photo.food.receipt')).toHaveLength(0);});
