import type { PhotoFoodOperation } from '@/agents/coach-assistant/photo-food-actions';
import type { PhotoFoodProposal, PhotoFoodResult } from '@/agents/coach-assistant/photo-food-contracts';
import type { PhotoFoodTransport } from './photo-food-client';

type Snapshot = Extract<PhotoFoodResult, { ok: true; snapshot: unknown }>['snapshot'];
type Receipt = Extract<PhotoFoodResult, { ok: true; receipt: unknown }>['receipt'];
export interface PhotoFoodState { attachmentId:string|null;snapshot:Snapshot|null;itemIndex:number|null;proposal:PhotoFoodProposal|null;receipt:Receipt|null;refreshEntryId:string|null;pending:boolean;uncertain:boolean;error:string|null }
const empty=():PhotoFoodState=>({attachmentId:null,snapshot:null,itemIndex:null,proposal:null,receipt:null,refreshEntryId:null,pending:false,uncertain:false,error:null});

export class PhotoFoodController {
 private state=empty();private listeners=new Set<()=>void>();private active:AbortController|null=null;private generation=0;private conversationId='';private action:Extract<PhotoFoodOperation,{operation:'photo.food.apply'}>|null=null;
 snapshot=()=>this.state;subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};private publish(state:PhotoFoodState){this.state=state;this.listeners.forEach(listener=>listener());}
 reset(){this.generation++;this.active?.abort();this.active=null;this.action=null;this.conversationId='';this.publish(empty());}
 moveConversation(conversationId:string){if(conversationId===this.conversationId)return;this.reset();this.conversationId=conversationId;}
 cancel(){if(!this.active)return;this.generation++;this.active.abort();this.active=null;this.publish({...this.state,pending:false,uncertain:Boolean(this.action&&!this.state.receipt),error:this.action?'uncertain':null});}
 dismiss(){if(this.action&&!this.state.receipt)return;this.reset();}
 async select(attachmentId:string,conversationId:string,transport:PhotoFoodTransport){if(this.action&&!this.state.receipt)return false;this.reset();this.conversationId=conversationId;this.publish({...empty(),attachmentId});await this.run({version:'coach-assistant.v2',operation:'photo.food.read',conversationId,turnId:crypto.randomUUID(),attachmentId},transport);return true;}
 choose(index:number){if(!this.state.pending&&this.state.snapshot?.items.some(item=>item.index===index))this.publish({...this.state,itemIndex:index,proposal:null,error:null});}
 async propose(after:{loggedDate:string;mealType:'breakfast'|'lunch'|'dinner'|'snack'|'pre_workout'|'post_workout';grams:number},transport:PhotoFoodTransport){const s=this.state,item=s.snapshot?.items.find(value=>value.index===s.itemIndex);if(!s.attachmentId||!s.snapshot||!item||s.pending||this.action||!Number.isFinite(after.grams)||after.grams<.1||after.grams>10000)return;await this.run({version:'coach-assistant.v2',operation:'photo.food.propose',conversationId:this.conversationId,turnId:crypto.randomUUID(),attachmentId:s.attachmentId,observationId:s.snapshot.observationId,itemIndex:item.index,resourceVersion:item.version,after},transport);}
 discard(){if(!this.state.pending&&!this.action)this.publish({...this.state,proposal:null,error:null});}
 async apply(transport:PhotoFoodTransport){const p=this.state.proposal;if(!p||this.state.pending||this.action||this.state.receipt)return;if(Date.parse(p.expiresAt)<=Date.now()){this.publish({...this.state,error:'expired'});return;}this.action={version:'coach-assistant.v2',operation:'photo.food.apply',conversationId:this.conversationId,turnId:crypto.randomUUID(),proposalId:p.id,hash:p.hash,actionId:crypto.randomUUID(),resourceVersion:p.resource.version,reviewed:true};await this.run(this.action,transport);}
 async check(transport:PhotoFoodTransport){if(!this.action||this.state.pending||!this.state.uncertain)return;await this.run({version:'coach-assistant.v2',operation:'photo.food.receipt',conversationId:this.conversationId,turnId:crypto.randomUUID(),actionId:this.action.actionId},transport);}
 private async run(operation:PhotoFoodOperation,transport:PhotoFoodTransport){const controller=new AbortController();this.active=controller;const generation=++this.generation,valid=()=>generation===this.generation&&!controller.signal.aborted;this.publish({...this.state,pending:true,error:null});try{const result=await transport(operation,controller.signal);if(!valid())return;if(!result.ok){if(result.error==='uncertain'&&this.action)this.publish({...this.state,pending:false,uncertain:true,error:'uncertain'});else this.publish({...this.state,pending:false,error:result.error});return;}if('snapshot'in result){if(result.snapshot.attachmentId!==this.state.attachmentId||result.snapshot.trust!=='untrusted_image_data'||result.snapshot.reviewRequired!==true)throw Error('invalid_snapshot');this.publish({...this.state,snapshot:result.snapshot,itemIndex:result.snapshot.items[0]?.index??null,pending:false});}else if('proposal'in result){const item=this.state.snapshot?.items.find(value=>value.index===this.state.itemIndex);if(!item||result.proposal.before!==null||result.proposal.precondition!==item.version||result.proposal.after.portion!=='explicit_user'||result.proposal.evidence.trust!=='untrusted_image_data')throw Error('invalid_proposal');this.publish({...this.state,proposal:result.proposal,pending:false});}else{if(!this.action||result.receipt.actionId!==this.action.actionId||result.refresh.entryId!==result.receipt.proposalId)throw Error('invalid_receipt');this.publish({...this.state,receipt:result.receipt,refreshEntryId:result.refresh.entryId,pending:false,uncertain:false});}}
 catch{if(valid())this.publish({...this.state,pending:false,uncertain:Boolean(this.action),error:this.action?'uncertain':'failed'});}finally{if(valid())this.active=null;}}
}
