import {sql} from 'drizzle-orm';
import {z} from 'zod';
import type {db} from '@/db/client';
import {authorizeCoachChat} from './chat-service';
import type {CoachChatScope} from './chat-contract';
type Database=typeof db;const uuid=z.string().uuid();
export interface CoachChatPrivateAttachmentErasurePort {remove(input:{attachmentId:string;actorId:string;subjectId:string;organizationId:string;conversationId:string;bucket:string;objectPath:string},signal:AbortSignal):Promise<{removed:false}|{removed:true;bucket:string;objectPath:string}>}
export interface CoachChatPrivacyExport {status:'complete'|'partial'|'not_connected'|'forbidden'|'cancelled';threads:unknown[];turnBindings:unknown[];memoryBindings:unknown[];attachments:unknown[];actionProposals:unknown[];actionReceipts:unknown[];photoFoodObservations:unknown[];unavailable:string[];truncated:string[];contentSource:'public.agent_conversation_export'}
const empty=(status:CoachChatPrivacyExport['status']):CoachChatPrivacyExport=>({status,threads:[],turnBindings:[],memoryBindings:[],attachments:[],actionProposals:[],actionReceipts:[],photoFoodObservations:[],unavailable:[],truncated:[],contentSource:'public.agent_conversation_export'});
const missing=(e:unknown)=>['42P01','42703','42883'].includes(String((e as {code?:string;cause?:{code?:string}})?.cause?.code??(e as {code?:string})?.code));
/** Metadata/private-ledger supplement to the existing public export. It never
 * repeats message text; turn bindings identify public.agent_conversation rows. */
export function createCoachChatPrivacy(database:Database){return {
 async export(scope:CoachChatScope,signal:AbortSignal):Promise<CoachChatPrivacyExport>{
  if(scope.actorId!==scope.subjectId||scope.actorRole!=='client')return empty('forbidden');const out=empty('complete');
  const collections=[
   ['threads',()=>sql`SELECT id,title,state,revision::text,created_at::text FROM private.coach_chat_threads WHERE actor_id=${scope.actorId}::uuid AND subject_id=${scope.actorId}::uuid AND organization_id=${scope.organizationId}::uuid ORDER BY created_at,id LIMIT 1001`],
   ['turnBindings',()=>sql`SELECT t.thread_id,t.content_id,t.turn_id,t.role,t.sequence,t.revision::text,t.current,t.pipeline_version FROM private.coach_chat_turns t JOIN private.coach_chat_threads h ON h.id=t.thread_id WHERE h.actor_id=${scope.actorId}::uuid AND h.subject_id=${scope.actorId}::uuid AND h.organization_id=${scope.organizationId}::uuid ORDER BY t.thread_id,t.sequence LIMIT 5001`],
   ['memoryBindings',()=>sql`SELECT memory_id,conversation_id,revision::text,confirmed_text_hash FROM private.coach_memory_bindings WHERE actor_id=${scope.actorId}::uuid AND subject_id=${scope.actorId}::uuid AND organization_id=${scope.organizationId}::uuid ORDER BY memory_id LIMIT 1001`],
   ['attachments',()=>sql`SELECT id,conversation_id,state,mime,input_bytes,metadata,created_at::text,expires_at::text FROM private.coach_attachment_uploads WHERE actor_id=${scope.actorId}::uuid AND subject_id=${scope.actorId}::uuid AND organization_id=${scope.organizationId}::uuid ORDER BY id LIMIT 1001`],
   ['actionProposals',()=>sql`SELECT id,conversation_id,action,resource_version,envelope,created_at::text,expires_at::text FROM private.coach_action_proposals WHERE actor_id=${scope.actorId}::uuid AND subject_id=${scope.actorId}::uuid AND organization_id=${scope.organizationId}::uuid ORDER BY id LIMIT 1001`],
   ['actionReceipts',()=>sql`SELECT id,conversation_id,action_id,proposal_id,resource_version,result,recorded_at::text FROM private.coach_action_receipts WHERE actor_id=${scope.actorId}::uuid AND subject_id=${scope.actorId}::uuid AND organization_id=${scope.organizationId}::uuid ORDER BY id LIMIT 1001`],
   ['photoFoodObservations',()=>sql`SELECT id,conversation_id,attachment_id,revision,image_digest,generation_id,foods,active,created_at::text FROM private.coach_photo_food_observations WHERE actor_id=${scope.actorId}::uuid AND subject_id=${scope.actorId}::uuid AND organization_id=${scope.organizationId}::uuid ORDER BY id LIMIT 1001`],
  ] as const;
  for(const [name,query] of collections){try{const rows=await database.transaction(async tx=>{await authorizeCoachChat(tx,scope,signal);const contract=await tx.execute<{version:string}>(sql`SELECT private.coach_chat_contract_version() AS version`);if(contract.rows[0]?.version!=='coach-assistant.chat.v1')throw Object.assign(Error('not connected'),{code:'42P01'});const result=await tx.execute(query());await authorizeCoachChat(tx,scope,signal);return result.rows;});const limit=name==='turnBindings'?5000:1000;if(rows.length>limit)out.truncated.push(name);(out[name] as unknown[])=rows.slice(0,limit);}catch(error){if(signal.aborted)return empty('cancelled');if(error instanceof Error&&error.message==='forbidden')return empty('forbidden');if(name==='threads'&&missing(error))return empty('not_connected');out.unavailable.push(name);}}
  out.status=out.unavailable.length||out.truncated.length?'partial':'complete';return out;
 },
 async eraseBeforeProfileDelete(userId:string,attachments:CoachChatPrivateAttachmentErasurePort|undefined,signal:AbortSignal):Promise<{status:'complete'|'pending'|'failed';remaining:number|null}>{
  userId=uuid.parse(userId);try{const found=await database.execute<{id:string;actor_id:string;subject_id:string;organization_id:string;conversation_id:string;bucket:string;object_path:string}>(sql`SELECT id,actor_id,subject_id,organization_id,conversation_id,bucket,object_path FROM private.coach_attachment_uploads WHERE (actor_id=${userId}::uuid OR subject_id=${userId}::uuid) AND state<>'removed' ORDER BY id LIMIT 1001`);if(found.rows.length&&!attachments)return {status:'pending',remaining:found.rows.length>1000?null:found.rows.length};
   for(const row of found.rows.slice(0,1000)){const input={attachmentId:row.id,actorId:row.actor_id,subjectId:row.subject_id,organizationId:row.organization_id,conversationId:row.conversation_id,bucket:row.bucket,objectPath:row.object_path};const result=await attachments!.remove(input,signal);if(!result.removed||result.bucket!==row.bucket||result.objectPath!==row.object_path)return {status:'failed',remaining:null};const marked=await database.execute(sql`UPDATE private.coach_attachment_uploads SET state='removed',metadata=NULL WHERE id=${row.id}::uuid AND actor_id=${row.actor_id}::uuid AND subject_id=${row.subject_id}::uuid AND organization_id=${row.organization_id}::uuid AND bucket=${row.bucket} AND object_path=${row.object_path} AND state<>'removed' RETURNING id`);if(marked.rows.length!==1)return {status:'failed',remaining:null};}
   return await database.transaction(async tx=>{const remaining=await tx.execute<{total:string}>(sql`SELECT count(*)::text AS total FROM private.coach_attachment_uploads WHERE (actor_id=${userId}::uuid OR subject_id=${userId}::uuid) AND state<>'removed'`);const total=Number(remaining.rows[0]?.total);if(!Number.isSafeInteger(total)||total<0)return {status:'failed' as const,remaining:null};if(total)return {status:'pending' as const,remaining:total};await tx.execute(sql`DELETE FROM private.coach_photo_food_observations WHERE actor_id=${userId}::uuid OR subject_id=${userId}::uuid`);await tx.execute(sql`DELETE FROM private.coach_attachment_uploads WHERE (actor_id=${userId}::uuid OR subject_id=${userId}::uuid) AND state='removed'`);return {status:'complete' as const,remaining:0};});
  }catch(error){return {status:missing(error)?'pending':'failed',remaining:null};}
 }
};}
