import {describe,expect,it,vi} from 'vitest';
import {decidePilotBudgetCommand,type PilotAttemptRecord,type PilotBudgetCommand,type PilotBudgetStore} from './pilot-budget';
import {runGovernedPilotModality} from './governed-modality';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(){const rows=new Map<string,PilotAttemptRecord>(),events:string[]=[];const store:PilotBudgetStore={execute:vi.fn(async(command:PilotBudgetCommand)=>{events.push(command.operation);const existing=rows.get(command.binding.attemptId);const decision=decidePilotBudgetCommand({pilotId:id(1),budgetDay:'2026-09-09',capNanoUsd:500_000_000,chargedNanoUsd:[...rows.values()].reduce((n,row)=>n+row.chargedNanoUsd,0),turnAttemptCount:[...rows.values()].filter(row=>row.binding.turnId===command.binding.turnId).length,accountingBlocked:false,existing},command);if(decision.ok&&decision.write!=='none')rows.set(command.binding.attemptId,structuredClone(decision.record));return {storage:'database' as const,...decision};})};return {store,rows,events};}
describe('shared governed modality admission',()=>{
 it('reserves and claims before one photo invocation, then settles measured Haiku usage',async()=>{const f=fixture(),run=vi.fn(async()=>({selectedPolicy:{provider:'anthropic',model:'claude-haiku-4-5-20251001',promptVersion:'photo-analyze-v1'},isFallback:false,usage:{inputTokens:1000,outputTokens:200},rawStatus:200,latencyMs:4,output:{ok:true}}));const result=await runGovernedPilotModality({pilotId:id(1),actorId:id(2),turnId:id(3),identityParts:[id(1),id(2),'photo',id(4)],task:'photo_analyze',store:f.store,signal:new AbortController().signal,run});expect(result.output).toEqual({ok:true});expect(f.events).toEqual(['reserve','claim_dispatch','settle']);expect(run).toHaveBeenCalledOnce();expect([...f.rows.values()][0]).toMatchObject({binding:{model:'claude-haiku-4-5-20251001'},state:'settled',chargedNanoUsd:2_000_000});});
 it('counts STT in the same store and preserves a dispatched timeout as unknown without retry',async()=>{const f=fixture(),run=vi.fn(async()=>{throw Object.assign(new Error('deadline'),{_isTimeout:true});});await expect(runGovernedPilotModality({pilotId:id(1),actorId:id(2),turnId:id(3),identityParts:[id(1),id(2),'stt',id(5)],task:'transcribe',store:f.store,signal:new AbortController().signal,run})).rejects.toThrow('provider_unavailable');expect(f.events).toEqual(['reserve','claim_dispatch','mark_unknown']);expect(run).toHaveBeenCalledOnce();expect([...f.rows.values()][0]).toMatchObject({binding:{model:'gpt-4o-mini-transcribe'},state:'unknown',chargedNanoUsd:30_000_000});});
 it('does not invoke a modality when admission is denied',async()=>{const run=vi.fn(),store:PilotBudgetStore={execute:vi.fn(async()=>({storage:'database',ok:false,error:'budget_blocked'}))};await expect(runGovernedPilotModality({pilotId:id(1),actorId:id(2),turnId:id(3),identityParts:[id(1),id(2),'photo',id(4)],task:'photo_analyze',store,signal:new AbortController().signal,run})).rejects.toThrow('budget_blocked');expect(run).not.toHaveBeenCalled();});
 it('uses a fresh bounded accounting signal to preserve unknown after request cancellation',async()=>{const f=fixture(),request=new AbortController(),run=vi.fn(async()=>{request.abort();throw new Error('cancelled');});await expect(runGovernedPilotModality({pilotId:id(1),actorId:id(2),turnId:id(3),identityParts:[id(1),id(2),'stt',id(6)],task:'transcribe',store:f.store,signal:request.signal,run})).rejects.toThrow('provider_unavailable');expect(f.events).toEqual(['reserve','claim_dispatch','mark_unknown']);expect(vi.mocked(f.store.execute).mock.calls[2][1].aborted).toBe(false);expect([...f.rows.values()][0]).toMatchObject({state:'unknown'});});
});
