/** Browser-only declarations. Numbers remain photo-derived estimates after portion review. */
export interface PhotoFoodReview {loggedDate:string;mealType:'breakfast'|'lunch'|'dinner'|'snack'|'pre_workout'|'post_workout';foodName:string;grams:number;calories:number;proteinG:number;carbsG:number;fatG:number;fiberG:number;sugarG:number;confidence:number;source:'photo_ai';nutrition:'estimated';portion:'explicit_user'}
export interface PhotoFoodEvidence {observationId:string;observationRevision:string;attachmentId:string;imageDigest:string;itemIndex:number;source:'validated_photo_analysis'|'offline_fixture';trust:'untrusted_image_data'}
export interface PhotoFoodProposal {id:string;hash:string;action:'food.photo.create';resource:{kind:'food_entry';id:string;version:string};before:null;after:PhotoFoodReview;evidence:PhotoFoodEvidence;precondition:string;expiresAt:string;reviewRequired:true}
export type PhotoFoodError='identity_clarification_required'|'invalid_input'|'forbidden'|'not_found'|'not_connected'|'version_conflict'|'expired'|'idempotency_conflict'|'uncertain'|'cancelled';
export type PhotoFoodResult={version:'coach-assistant.v2';evaluation?:{mode:'isolated_authorized_fixture';observation:'offline_fixture';visionVerified:false;paidApiCalls:0}}&(
 {ok:false;storage:'database';error:PhotoFoodError}|
 {ok:true;storage:'database'|'offline_fixture'|'isolated_database_fixture';snapshot:{observationId:string;attachmentId:string;source:'validated_photo_analysis'|'offline_fixture';trust:'untrusted_image_data';reviewRequired:true;items:Array<{index:number;version:string;foodName:string;estimatedGrams:number;estimatedCalories:number;confidence:number;accuracyNote:string;identityStatus?:'identified'|'uncertain'|'unassessed'}>}}|
 {ok:true;storage:'database'|'offline_fixture'|'isolated_database_fixture';proposal:PhotoFoodProposal}|
 {ok:true;storage:'database'|'isolated_database_fixture';receipt:{id:string;actionId:string;proposalId:string;status:'applied';action:'food.photo.create';resourceVersion:string;recordedAt:string};refresh:{entryId:string;loggedDate:string;previousVersion:string;version:string;strategy:'refetch'}});
