import {describe,it,expect} from 'vitest';
import {PgDialect} from 'drizzle-orm/pg-core';
import {createPhotoFoodService} from './photo-food-service';
import {createIsolatedPhotoFoodBoundary} from './photo-food-isolation';
import {createOfflinePhotoFoodObservationPort,validatePhotoFoodObservation,type PhotoFoodObservationPort} from './photo-food-observation';
import {executePhotoFoodAction,type PhotoFoodOperation} from './photo-food-actions';
import {fixtureRepository} from './fixtures';
import type {PhotoFoodProposal} from './photo-food-contracts';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor=id(1),org=id(2),attachmentId=id(3),base={version:'coach-assistant.v2' as const,conversationId:id(4),turnId:id(5)};
const photo={name:'Rice',estimated_grams:100,estimated_calories:130,estimated_protein_g:2.7,estimated_carbs_g:28,estimated_fat_g:0.3,estimated_fiber_g:0.4,estimated_sugar_g:0,confidence:0.9,source:'ai_estimate',accuracy_note:'Photo estimate; confirm portion.'};
const rawObservation={actorId:actor,subjectId:actor,organizationId:org,conversationId:base.conversationId,attachmentId,id:id(6),revision:id(7),imageDigest:'a'.repeat(64),source:'offline_fixture' as const,foods:[photo]};
/** All numbers and observations are synthetic test data, including the injected
 * guarded offline observation port. No image interpretation, database or API is executed. */
const isolationEnv=()=>({CI:'true',GITHUB_ACTIONS:'true',CI_REAL_SUPABASE:'1',COACH_ASSISTANT_ISOLATED_ENGINE_ENABLED:'1',COACH_ASSISTANT_ISOLATED_PHOTO_FOOD_ENABLED:'1',COACH_ASSISTANT_DATA_SOURCE:'authorized_records',DATABASE_URL:'postgresql://fixture:fixture@127.0.0.1:54322/postgres',NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:54321',VERCEL_ENV:'preview'});
function fixture(offline=false){
 const observation=structuredClone(rawObservation),env=isolationEnv();let authorized=true,available=true,expired=false,revision=true,receiptFails=false,auditFails=false,lost=false,corrupt=false,writes=0,audits=0;
 let proposals:Record<string,Record<string,unknown>>={},receipts:Record<string,Record<string,unknown>>={},rows:Record<string,unknown>[]=[];const queries:Array<{sql:string;params:unknown[]}>=[];
 const controller=new AbortController();let abortInsert=false;
 const tx={insert:()=>({values:(v:Record<string,unknown>)=>({returning:async()=>{writes++;rows.push(v);if(abortInsert)controller.abort();return [{...v,...(corrupt?{source:'custom'}:{})}];}})}),execute:async(q:Parameters<PgDialect['sqlToQuery']>[0])=>{
  const {sql,params:p}=new PgDialect().sqlToQuery(q);queries.push({sql,params:p});
  if(sql.includes('FROM public.profiles actor'))return {rows:authorized&&p[0]===actor&&p[1]===actor&&p[2]===org?[{id:actor}]:[]};
  if(sql.includes('FROM private.coach_action_receipts r'))return {rows:receipts[String(p[1])]?[receipts[String(p[1])]]:[]};
  if(sql.includes('SELECT normalized_digest,state'))return {rows:p[0]===attachmentId&&p[1]===actor&&p[2]===actor&&p[3]===org&&p[4]===base.conversationId?[{normalized_digest:'a'.repeat(64),state:available?'available':'removed',expired}]:[]};
  if(sql.includes("interval '5 minutes'"))return {rows:[{expires:'2026-09-07T12:05:00Z'}]};
  if(sql.includes('SELECT count(*)::text'))return {rows:[{count:String(Object.keys(proposals).length)}]};
  if(sql.includes('INSERT INTO private.coach_action_proposals')){proposals[String(p[0])]={envelope:JSON.parse(String(p[8])),request_hash:p[6],resource_version:p[7],subject_id:p[2],organization_id:p[3],conversation_id:p[4],expired:false};return {rows:[]};}
  if(sql.includes('SELECT envelope,request_hash')){const saved=proposals[String(p[0])];return {rows:saved&&saved.subject_id===p[2]&&saved.organization_id===p[3]&&saved.conversation_id===p[4]?[{...saved,expired}]:[]};}
  if(sql.includes('SELECT id FROM private.coach_action_receipts'))return {rows:Object.values(receipts).filter(r=>r.proposal_id===p[1])};
  if(sql.includes('SELECT clock_timestamp()>='))return {rows:[{expired}]};
  if(sql.includes('SELECT revision::text'))return {rows:revision?[{revision:'1'}]:[]};
  if(sql.includes(' AS recorded'))return {rows:[{recorded:'2026-09-07T12:01:00Z'}]};
  if(sql.includes('INSERT INTO private.coach_action_receipts')){if(receiptFails)throw Error('receipt failed');receipts[String(p[5])]={subject_id:p[2],organization_id:p[3],conversation_id:p[4],proposal_id:p[6],request_hash:p[7],resource_version:p[8],result:JSON.parse(String(p[9])),action:'food.photo.create',envelope:proposals[String(p[6])].envelope};return {rows:[]};}
  if(sql.includes('INSERT INTO public.audit_log')){if(auditFails)throw Error('audit failed');audits++;return {rows:[]};}
  if(sql.includes('SET LOCAL')||sql.includes('pg_advisory_xact_lock'))return {rows:[]};throw Error(`Unexpected query ${sql}`);
 }};
 const database={$client:{options:{connectionString:env.DATABASE_URL}},transaction:async(work:(value:typeof tx)=>Promise<unknown>)=>{const before=structuredClone({rows,writes,audits,receipts,proposals});let out:unknown;try{out=await work(tx);}catch(e){({rows,writes,audits,receipts,proposals}=before);throw e;}if(lost){lost=false;throw Error('lost commit');}return out;}} as unknown as Parameters<typeof createPhotoFoodService>[0];
 const port:PhotoFoodObservationPort=offline?createOfflinePhotoFoodObservationPort([rawObservation]):{load:async(_scope,signal,transaction)=>{expect(transaction).toBe(tx);signal.throwIfAborted();return structuredClone(observation);}};
 const fixtureScope={actorId:actor,subjectId:actor,organizationId:org,conversationId:base.conversationId,attachmentId};
 const boundary=offline?undefined:createIsolatedPhotoFoodBoundary(env,database,port,[fixtureScope]);
 const service=createPhotoFoodService(database,port,boundary),execute=(operation:PhotoFoodOperation)=>service.execute({actorId:actor,subjectId:actor,organizationId:org,operation,signal:controller.signal});
 const read=async()=>execute({...base,operation:'photo.food.read',attachmentId});
 const propose=async()=>{const r=await read();if(!r.ok||!('snapshot' in r))throw Error(JSON.stringify(r));const result=await execute({...base,operation:'photo.food.propose',attachmentId,observationId:r.snapshot.observationId,itemIndex:0,resourceVersion:r.snapshot.items[0].version,after:{loggedDate:'2026-09-07',mealType:'lunch',grams:150}});if(!result.ok||!('proposal' in result))throw Error(JSON.stringify(result));return result.proposal;};
 const apply=(p:PhotoFoodProposal)=>({...base,operation:'photo.food.apply' as const,proposalId:p.id,hash:p.hash,resourceVersion:p.resource.version,actionId:id(8),reviewed:true as const});
 return {database,service,execute,env,port,boundary,fixtureScope,read,propose,apply,queries,state:()=>({rows,writes,audits,proposals,receipts}),revoke:()=>{authorized=false;},remove:()=>{available=false;},expire:()=>{expired=true;},change:()=>{observation.revision=id(99);},foreign:()=>{observation.subjectId=id(99);},digest:()=>{observation.imageDigest='b'.repeat(64);},failReceipt:()=>{receiptFails=true;},failAudit:()=>{auditFails=true;},noRevision:()=>{revision=false;},corrupt:()=>{corrupt=true;},lose:()=>{lost=true;},deleteEntry:()=>{rows=[];},abort:()=>controller.abort(),abortInsert:()=>{abortInsert=true;}};
}
describe('photo observation to reviewed Food creation with injected transactions',()=>{
 it('reads estimates and prepares explicit 150g using existing portion math without saving food',async()=>{const f=fixture();expect(await f.read()).toMatchObject({storage:'isolated_database_fixture',evaluation:{observation:'offline_fixture',visionVerified:false,paidApiCalls:0},snapshot:{source:'offline_fixture',reviewRequired:true,items:[{estimatedGrams:100,confidence:0.75}]}});const p=await f.propose();expect(p.after).toMatchObject({grams:150,calories:195,proteinG:4.1,carbsG:42,fatG:0.5,source:'photo_ai',nutrition:'estimated',portion:'explicit_user'});expect(f.state().writes).toBe(0);});
 it('labels offline fixtures and never persists a proposal, food entry or receipt for them',async()=>{const f=fixture(true);expect(await f.read()).toMatchObject({storage:'offline_fixture',snapshot:{source:'offline_fixture'}});const p=await f.propose();expect(p.evidence.source).toBe('offline_fixture');expect(f.state()).toMatchObject({proposals:{},rows:[],receipts:{}});expect(await f.execute(f.apply(p))).toMatchObject({error:'not_found'});});
 it('applies reviewed creation once through shared writer and recovers after food and attachment removal',async()=>{const f=fixture(),p=await f.propose(),op=f.apply(p),result=await f.execute(op);expect(result).toMatchObject({receipt:{status:'applied',action:'food.photo.create'},refresh:{entryId:p.id}});expect(f.state()).toMatchObject({writes:1,audits:1,rows:[{qtyG:'150',source:'photo_ai',foodId:null}]});expect(await f.execute(op)).toEqual(result);f.deleteEntry();f.remove();expect(await f.execute({...base,operation:'photo.food.receipt',actionId:id(8)})).toEqual(result);expect(await f.execute({...op,actionId:id(9)})).toMatchObject({error:'idempotency_conflict'});expect(f.state().writes).toBe(1);});
 it('rejects changed observation, image digest, removed attachment, expiry and foreign scope before write',async()=>{for(const kind of ['change','digest','remove','expire','foreign'] as const){const f=fixture(),p=await f.propose();f[kind]();expect(await f.execute(f.apply(p))).toMatchObject({error:kind==='remove'?'not_found':kind==='expire'?'expired':kind==='foreign'?'forbidden':'version_conflict'});expect(f.state().writes).toBe(0);}});
 it('rolls back shared insertion on receipt, audit, revision, provenance or cancellation failures',async()=>{for(const kind of ['failReceipt','failAudit','noRevision','corrupt','abortInsert'] as const){const f=fixture(),p=await f.propose();f[kind]();expect(await f.execute(f.apply(p))).toMatchObject({error:kind==='noRevision'?'not_connected':'uncertain'});expect(f.state()).toMatchObject({rows:[],writes:0,audits:0,receipts:{}});}});
 it('recovers a lost committed acknowledgement and scopes replay to actor/org/conversation',async()=>{const f=fixture(),p=await f.propose(),op=f.apply(p);f.lose();expect(await f.execute(op)).toMatchObject({error:'uncertain'});expect(f.state().writes).toBe(1);expect(await f.execute(op)).toMatchObject({receipt:{status:'applied'}});expect(await f.execute({...op,conversationId:id(99)})).toMatchObject({error:'idempotency_conflict'});expect(await f.service.execute({actorId:actor,subjectId:actor,organizationId:id(99),operation:op,signal:new AbortController().signal})).toMatchObject({error:'forbidden'});f.revoke();expect(await f.execute(op)).toMatchObject({error:'forbidden'});});
 it('requires explicit portion/date/meal and human review, rejects arbitrary macros and missing observation adapter',async()=>{const f=fixture(),p=await f.propose();expect(await f.execute({...f.apply(p),reviewed:false} as unknown as PhotoFoodOperation)).toMatchObject({error:'invalid_input'});const op={...base,operation:'photo.food.propose',attachmentId,observationId:id(6),itemIndex:0,resourceVersion:p.resource.version,after:{loggedDate:'2026-09-07',mealType:'lunch',grams:150}};for(const after of [{...op.after,grams:undefined},{...op.after,calories:10},{...op.after,grams:0.001},{...op.after,loggedDate:'2026-02-30'}])expect(await f.execute({...op,after} as PhotoFoodOperation)).toMatchObject({error:'invalid_input'});expect(await createPhotoFoodService(f.database).execute({actorId:actor,subjectId:actor,organizationId:org,signal:new AbortController().signal,operation:{...base,operation:'photo.food.read',attachmentId}})).toMatchObject({error:'not_connected'});});
 it('validates bounded observations without dropping indices or accepting dish-prior guesses',()=>{const scope={actorId:actor,subjectId:actor,organizationId:org,conversationId:base.conversationId,attachmentId};for(const foods of [[],Array(9).fill(photo),[photo,{...photo,estimated_grams:0}],[{...photo,needs_confirmation:true}]])expect(()=>validatePhotoFoodObservation({...rawObservation,foods},scope)).toThrow();expect(()=>validatePhotoFoodObservation({...rawObservation,subjectId:id(99)},scope)).toThrow('forbidden');});
 it('wrapper derives server context and rejects authorization drift without a second write',async()=>{const f=fixture(),repo=fixtureRepository();Object.defineProperty(repo,'dataSource',{value:'authorized_records'});const context={actorId:actor,subjectId:actor,organizationId:org,timezone:'UTC',language:'en'};repo.authorize=async()=>context;const op={...base,operation:'photo.food.read' as const,attachmentId};expect(await executePhotoFoodAction(actor,op,repo,f.service,new AbortController().signal)).toMatchObject({snapshot:{observationId:id(6)}});let count=0;repo.authorize=async()=>++count===1?context:{...context,organizationId:id(99)};expect(await executePhotoFoodAction(actor,op,repo,f.service,new AbortController().signal)).toMatchObject({error:'forbidden'});});
 it('requires the exact CI guard, live pool binding, original capability and fixture scope',async()=>{
  const f=fixture();for(const change of [{CI:'false'},{GITHUB_ACTIONS:'false'},{CI_REAL_SUPABASE:'0'},{VERCEL_ENV:'production'},{TROPHE_ALLOW_PAID_AI:'1'},{COACH_ASSISTANT_ISOLATED_PHOTO_FOOD_ENABLED:'0'},{DATABASE_URL:'postgresql://fixture@remote.invalid/postgres'},{NEXT_PUBLIC_SUPABASE_URL:'https://remote.invalid'}])expect(()=>createIsolatedPhotoFoodBoundary({...isolationEnv(),...change},f.database,f.port,[f.fixtureScope])).toThrow();
  const p=await f.propose(),op=f.apply(p),scope={actorId:actor,subjectId:actor,organizationId:org,signal:new AbortController().signal,operation:op};
  expect(await createPhotoFoodService(f.database,f.port,{kind:'isolated_photo_food_fixture'}).execute(scope)).toMatchObject({error:'not_connected'});
  expect(await createPhotoFoodService(f.database,{load:f.port.load},f.boundary).execute(scope)).toMatchObject({error:'not_connected'});
  const other=createIsolatedPhotoFoodBoundary(f.env,f.database,f.port,[{...f.fixtureScope,attachmentId:id(90)}]);expect(await createPhotoFoodService(f.database,f.port,other).execute(scope)).toMatchObject({error:'not_connected'});
  f.env.CI='false';expect(await f.execute(op)).toMatchObject({error:'not_connected'});expect(f.state().writes).toBe(0);
 });
 it('retains unmistakable fixture metadata through apply/recovery and blocks normal service recovery',async()=>{
  const f=fixture(),p=await f.propose(),op=f.apply(p),result=await f.execute(op);expect(p.evidence.source).toBe('offline_fixture');expect(result).toMatchObject({storage:'isolated_database_fixture',evaluation:{mode:'isolated_authorized_fixture',observation:'offline_fixture',visionVerified:false,paidApiCalls:0},receipt:{status:'applied'}});
  expect(await f.execute({...base,operation:'photo.food.receipt',actionId:id(8)})).toEqual(result);
  expect(await createPhotoFoodService(f.database,f.port).execute({actorId:actor,subjectId:actor,organizationId:org,signal:new AbortController().signal,operation:{...base,operation:'photo.food.receipt',actionId:id(8)}})).toMatchObject({error:'not_connected'});
  f.database.$client.options.connectionString='postgresql://fixture@remote.invalid/postgres';expect(await f.execute(op)).toMatchObject({error:'not_connected'});
 });

});
