import {describe,it,expect} from 'vitest';
import {PgDialect} from 'drizzle-orm/pg-core';
import {createProgressService} from './progress-service';
import {executeProgressAction,type ProgressOperation} from './progress-actions';
import {fixtureRepository} from './fixtures';
import type {MeasurementProposal,ProgressResult} from './progress-contracts';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor=id(1),org=id(2),base={version:'coach-assistant.v2' as const,conversationId:id(3),turnId:id(4)};
const after={measuredDate:'2026-09-07',weightKg:70.1,bodyFatPct:null,waistCm:80};
type Raw={id:string;user_id:string;measured_date:string;weight_kg:unknown;body_fat_pct:unknown;waist_cm:unknown};
/** Transactional injected SQL fixture. Does NOT execute PostgreSQL, RLS or triggers. */
function fixture(){
 let revision=1,proposals:Record<string,Record<string,unknown>>={},receipts:Record<string,Record<string,unknown>>={},rows:Raw[]=[],writes=0,audits=0;
 let authorized=true,missingVersion=false,advance=true,receiptFails=false,auditFails=false,lostCommit=false,expired=false,corruptReturn=false;
 const statements:Array<{sql:string;params:unknown[]}>=[];const controller=new AbortController();let abortOnInsert=false;
 const tx={insert:()=>({values:(v:{id:string;userId:string;measuredDate:string;weightKg:number;bodyFatPct:number|null;waistCm:number|null})=>({returning:async()=>{writes++;rows.push({id:v.id,user_id:v.userId,measured_date:v.measuredDate,weight_kg:v.weightKg,body_fat_pct:v.bodyFatPct,waist_cm:v.waistCm});if(advance)revision++;if(abortOnInsert)controller.abort();return [{...v,weightKg:corruptReturn?90:Math.fround(v.weightKg)}];}})}),
 execute:async(q:Parameters<PgDialect['sqlToQuery']>[0])=>{
  const {sql,params:p}=new PgDialect().sqlToQuery(q);statements.push({sql,params:p});
  if(sql.includes('FROM public.profiles actor'))return {rows:authorized&&p[0]===actor&&p[1]===actor&&p[2]===org?[{timezone:'America/Bogota'}]:[]};
  if(sql.includes('FROM private.coach_action_receipts r'))return {rows:receipts[String(p[1])]?[receipts[String(p[1])]]:[]};
  if(sql.includes('SELECT revision::text'))return {rows:missingVersion?[]:[{revision:String(revision)}]};
  if(sql.includes(' AS start,'))return {rows:[{start:'2026-08-09',end:'2026-09-07'}]};
  if(sql.includes('FROM public.measurements'))return {rows:structuredClone(rows)};
  if(sql.includes('SELECT count(*)::text'))return {rows:[{count:String(Object.keys(proposals).length)}]};
  if(sql.includes("interval '5 minutes'"))return {rows:[{expires:'2026-09-07T12:05:00Z'}]};
  if(sql.includes('INSERT INTO private.coach_action_proposals')){proposals[String(p[0])]={envelope:JSON.parse(String(p[8])),expired:false,request_hash:p[6],resource_version:p[7],action:p[5],subject_id:p[2],organization_id:p[3],conversation_id:p[4]};return {rows:[]};}
  if(sql.includes('SELECT envelope,expires_at')){const found=proposals[String(p[0])];return {rows:found&&found.subject_id===p[2]&&found.organization_id===p[3]&&found.conversation_id===p[4]?[{...found,expired}]:[]};}
  if(sql.includes('SELECT id FROM private.coach_action_receipts'))return {rows:Object.values(receipts).filter(r=>r.proposal_id===p[1])};
  if(sql.includes('SELECT clock_timestamp()>='))return {rows:[{expired}]};
  if(sql.includes(' AS recorded'))return {rows:[{recorded:'2026-09-07T12:01:00Z'}]};
  if(sql.includes('INSERT INTO private.coach_action_receipts')){if(receiptFails)throw Error('receipt failed');receipts[String(p[5])]={subject_id:p[2],organization_id:p[3],conversation_id:p[4],proposal_id:p[6],request_hash:p[7],resource_version:p[8],result:JSON.parse(String(p[9])),action:'measurement.create'};return {rows:[]};}
  if(sql.includes('INSERT INTO public.audit_log')){if(auditFails)throw Error('audit failed');audits++;return {rows:[]};}
  if(sql.includes('SET LOCAL')||sql.includes('pg_advisory_xact_lock'))return {rows:[]};
  throw Error(`Unexpected fixture query: ${sql}`);
 }};
 const database={transaction:async(work:(value:typeof tx)=>Promise<unknown>)=>{const previous=structuredClone({revision,proposals,receipts,rows,writes,audits});let result:unknown;try{result=await work(tx);}catch(e){({revision,proposals,receipts,rows,writes,audits}=previous);throw e;}if(lostCommit){lostCommit=false;throw Error('commit response lost');}return result;}} as unknown as Parameters<typeof createProgressService>[0];
 const service=createProgressService(database),execute=(operation:ProgressOperation)=>service.execute({actorId:actor,subjectId:actor,organizationId:org,signal:controller.signal,operation});
 const propose=async()=>{const r=await execute({...base,operation:'measurement.propose',resourceVersion:String(revision),after,inputSource:'explicit_user'});expect(r).toMatchObject({ok:true});return (r as {proposal:MeasurementProposal}).proposal;};
 const apply=(p:MeasurementProposal)=>({...base,operation:'measurement.apply' as const,proposalId:p.id,hash:p.hash,resourceVersion:p.resource.version,actionId:id(5),reviewed:true as const});
 return {service,execute,propose,apply,statements,state:()=>({revision,rows,writes,audits,receipts}),seed:(v:Raw[])=>{rows=v;},mutate:()=>{revision++;},remove:()=>{rows=[];revision++;},revoke:()=>{authorized=false;},missing:()=>{missingVersion=true;},noTrigger:()=>{advance=false;},failReceipt:()=>{receiptFails=true;},failAudit:()=>{auditFails=true;},lose:()=>{lostCommit=true;},expire:()=>{expired=true;},corrupt:()=>{corruptReturn=true;},abort:()=>{controller.abort();},abortInsert:()=>{abortOnInsert=true;},tamper:(p:MeasurementProposal)=>{(proposals[p.id].envelope as MeasurementProposal).after.weightKg=80;}};
}
const raw=(n:number,date:string,weight:unknown,body:unknown=null):Raw=>({id:id(n),user_id:actor,measured_date:date,weight_kg:weight,body_fat_pct:body,waist_cm:null});
describe('Progress deterministic read and reviewed explicit creation',()=>{
 it('reads only the bounded profile-zone window and reports empty data without expanding it',async()=>{const f=fixture();expect(await f.execute({...base,operation:'progress.read',days:30})).toMatchObject({ok:true,snapshot:{window:{start:'2026-08-09',end:'2026-09-07',timezone:'America/Bogota',days:30},measurements:[],trends:[{change:null},{change:null},{change:null}],truncated:false}});const q=f.statements.find(q=>q.sql.includes('FROM public.measurements'))!;expect(q.sql).toContain('LIMIT 251');expect(q.params).toEqual([actor,'2026-08-09','2026-09-07']);expect(f.statements.find(q=>q.sql.includes(' AS start,'))!.params).toEqual(['America/Bogota',30,'America/Bogota']);});
 it('deduplicates IDs, excludes invalid values and aggregates only actual same-date observations',async()=>{const f=fixture(),r=raw(10,'2026-09-07',74);f.seed([r,r,raw(11,'2026-09-07',72),raw(12,'2026-09-01',70),raw(13,'2026-08-30',NaN,101)]);const result=await f.execute({...base,operation:'progress.read',days:30});expect(result).toMatchObject({snapshot:{duplicateRowsDropped:1,invalidValuesExcluded:2,trends:[{observations:3,days:2,first:{value:70},last:{value:73},change:3,aggregation:'daily_mean'},{change:null},{change:null}]}});});
 it('marks row truncation and fails closed for conflicting duplicate identity or foreign/window rows',async()=>{const f=fixture();f.seed(Array.from({length:251},(_,i)=>raw(i+100,'2026-09-07',70)));expect(await f.execute({...base,operation:'progress.read',days:30})).toMatchObject({snapshot:{truncated:true,trends:[{observations:250,change:null},{change:null},{change:null}]}});for(const rows of [[raw(10,'2026-09-07',70),raw(10,'2026-09-07',71)],[{...raw(10,'2026-09-07',70),user_id:id(99)}],[raw(10,'2026-01-01',70)]]){f.seed(rows);expect(await f.execute({...base,operation:'progress.read',days:30})).toMatchObject({error:'uncertain'});}});
 it('proposes without inserting, applies once and recovers a historical receipt after deletion',async()=>{const f=fixture(),p=await f.propose();expect(p).toMatchObject({after,before:null,inputSource:'explicit_user',reviewRequired:true});expect(p.id).toBe(p.resource.id);expect(f.state().writes).toBe(0);const apply=f.apply(p),r=await f.execute(apply);expect(r).toMatchObject({receipt:{status:'applied',action:'measurement.create',resourceVersion:'2'},refresh:{measurementId:p.id}});expect(f.state()).toMatchObject({writes:1,audits:1});expect(await f.execute(apply)).toEqual(r);f.remove();expect(await f.execute({...base,operation:'measurement.receipt',actionId:id(5)})).toEqual(r);expect(await f.execute({...apply,actionId:id(6)})).toMatchObject({error:'idempotency_conflict'});expect(f.state().writes).toBe(1);expect(f.statements.find(q=>q.sql.includes('SELECT envelope,expires_at'))!.sql).toContain('FOR UPDATE');});
 it('rejects CAS drift, expired proposal and hash mutation',async()=>{for(const kind of ['mutate','expire','tamper'] as const){const f=fixture(),p=await f.propose();if(kind==='tamper')f.tamper(p);else f[kind]();expect(await f.execute(f.apply(p))).toMatchObject({error:kind==='mutate'?'version_conflict':kind==='expire'?'expired':'invalid_input'});expect(f.state().writes).toBe(0);}});
 it('rolls back measurement, revision, audit and receipt on each injected failure',async()=>{for(const kind of ['failReceipt','failAudit','noTrigger','corrupt','abortInsert'] as const){const f=fixture(),p=await f.propose();f[kind]();expect(await f.execute(f.apply(p))).toMatchObject({error:'uncertain'});expect(f.state()).toMatchObject({rows:[],revision:1,writes:0,audits:0,receipts:{}});}});
 it('recovers committed-but-lost response without repeating insertion',async()=>{const f=fixture(),p=await f.propose();f.lose();expect(await f.execute(f.apply(p))).toMatchObject({error:'uncertain'});expect(f.state().writes).toBe(1);expect(await f.execute(f.apply(p))).toMatchObject({receipt:{status:'applied'}});expect(f.state().writes).toBe(1);});
 it('revalidates actor/org, scopes receipts to conversation and denies unreviewed or implicit values',async()=>{const f=fixture(),p=await f.propose();const op=f.apply(p);await f.execute(op);expect(await f.execute({...op,conversationId:id(99)})).toMatchObject({error:'idempotency_conflict'});expect(await f.service.execute({actorId:actor,subjectId:actor,organizationId:id(99),signal:new AbortController().signal,operation:op})).toMatchObject({error:'forbidden'});expect(await f.execute({...op,reviewed:false} as unknown as ProgressOperation)).toMatchObject({error:'invalid_input'});expect(await f.execute({...base,operation:'measurement.propose',resourceVersion:'2',after,inputSource:'photo'} as unknown as ProgressOperation)).toMatchObject({error:'invalid_input'});f.revoke();expect(await f.execute(op)).toMatchObject({error:'forbidden'});});
 it('fails closed without revision schema and cancels before dispatch',async()=>{const f=fixture();f.missing();expect(await f.execute({...base,operation:'progress.read',days:30})).toMatchObject({error:'not_connected'});f.abort();expect(await f.execute({...base,operation:'progress.read',days:30})).toMatchObject({error:'cancelled'});});
 it('server wrapper derives scope and rejects mismatched results or authorization drift',async()=>{const repo=fixtureRepository();Object.defineProperty(repo,'dataSource',{value:'authorized_records'});const context={actorId:actor,subjectId:actor,organizationId:org,timezone:'America/Bogota',language:'es'};repo.authorize=async()=>context;const f=fixture();const op={...base,operation:'measurement.propose' as const,resourceVersion:'1',after,inputSource:'explicit_user' as const};expect(await executeProgressAction(actor,op,repo,f.service,new AbortController().signal)).toMatchObject({proposal:{after}});const service={execute:async()=>({version:base.version,storage:'database',ok:true,proposal:{...(await f.propose()),precondition:'99'}} as ProgressResult)};expect(await executeProgressAction(actor,op,repo,service,new AbortController().signal)).toMatchObject({error:'uncertain'});let calls=0;repo.authorize=async()=>++calls===1?context:{...context,organizationId:id(99)};expect(await executeProgressAction(actor,op,repo,f.service,new AbortController().signal)).toMatchObject({error:'forbidden'});});
});
