'use client';

import { TrendingUp } from 'lucide-react';

export interface ExerciseProgressEntry { date: string; weightKg: number | null; reps: number | null; }
export function ExerciseProgressChart({ exerciseName, data }: { exerciseName: string; data: ExerciseProgressEntry[] }) {
  const evidence = data.filter((entry) => (entry.weightKg ?? 0) > 0 && (entry.reps ?? 0) > 0).sort((a, b) => a.date.localeCompare(b.date));
  if (!evidence.length) return <section className="rounded-xl bg-[var(--surface-subtle)] p-4"><h2 className="text-base font-semibold text-[var(--content-primary)]">Exercise progress</h2><p className="mt-3 text-sm text-[var(--content-muted)]">No completed weighted sets are available for this exercise yet.</p></section>;
  if (evidence.length < 2) return <section className="rounded-xl bg-[var(--surface-subtle)] p-4"><h2 className="text-base font-semibold text-[var(--content-primary)]">Exercise progress</h2><p className="mt-3 text-sm text-[var(--content-muted)]">Need at least two completed weighted sets to show progress evidence.</p></section>;
  const maxWeight = Math.max(...evidence.map((entry) => entry.weightKg ?? 0), 1);
  return <section className="rounded-xl bg-[var(--surface-subtle)] p-4" aria-labelledby="exercise-progress-title"><div className="mb-4 flex items-center gap-2"><TrendingUp size={17} className="text-[var(--action-primary)]" /><h2 id="exercise-progress-title" className="text-base font-semibold text-[var(--content-primary)]">{exerciseName} progress</h2></div><svg role="img" aria-label={`${exerciseName} completed weight progression`} viewBox="0 0 300 96" className="w-full" style={{ maxHeight: 144 }}><path d={`M 12 ${84 - ((evidence[0].weightKg ?? 0) / maxWeight) * 64} ${evidence.slice(1).map((entry, index) => `L ${12 + ((index + 1) / (evidence.length - 1)) * 276} ${84 - ((entry.weightKg ?? 0) / maxWeight) * 64}`).join(' ')}`} fill="none" stroke="var(--action-primary)" strokeWidth="3" strokeLinecap="round" />{evidence.map((entry, index) => <circle key={`${entry.date}-${index}`} cx={12 + (index / (evidence.length - 1)) * 276} cy={84 - ((entry.weightKg ?? 0) / maxWeight) * 64} r="3.5" fill="var(--action-primary)" />)}</svg><table className="mt-3 w-full text-left text-sm" aria-label={`${exerciseName} progress values`}><thead className="text-[var(--content-muted)]"><tr><th className="py-2 font-medium">Date</th><th className="py-2 font-medium">Weight</th><th className="py-2 font-medium">Reps</th><th className="py-2 text-right font-medium">Volume</th></tr></thead><tbody>{evidence.map((entry, index) => <tr key={`${entry.date}-${index}`} aria-label={`${entry.weightKg} kg, ${entry.reps} reps, ${entry.weightKg! * entry.reps!} kg volume`} className="border-t border-[var(--border-default)] text-[var(--content-secondary)]"><td className="py-2">{entry.date}</td><td className="py-2 tabular-nums">{entry.weightKg} kg</td><td className="py-2 tabular-nums">{entry.reps} reps</td><td className="py-2 text-right tabular-nums">{(entry.weightKg! * entry.reps!)} kg volume</td></tr>)}</tbody></table></section>;
}
