'use client';

import { memo, useState, useMemo, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Copy, Eye, EyeOff, FileText, Check } from 'lucide-react';

interface ClientReportData {
  name: string;
  email: string;
  goal: string;
  macros: Record<string, number>;
  habitsCompleted: number;
  currentHabit: string;
  recentNotes: Array<{ text: string; date: string }>;
  weightTrend: string;
  adherence: number;
}

interface ExportClientReportProps {
  client: ClientReportData;
}

function generateMarkdown(c: ClientReportData): string {
  const macroLines = Object.entries(c.macros)
    .map(([key, val]) => `- **${key}**: ${val}`)
    .join('\n');

  const noteLines =
    c.recentNotes.length > 0
      ? c.recentNotes.map((n) => `- [${n.date}] ${n.text}`).join('\n')
      : '- No recent notes';

  return `# Client Report: ${c.name}
**Email:** ${c.email}
**Goal:** ${c.goal}
**Date:** ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

---

## Macro Targets
${macroLines}

## Habit Progress
- **Current Habit:** ${c.currentHabit}
- **Habits Completed:** ${c.habitsCompleted}
- **Adherence:** ${c.adherence}%

## Weight Trend
${c.weightTrend}

## Recent Coach Notes
${noteLines}

---
*Generated by Troph\u0113 Coach Platform*`;
}

export default memo(function ExportClientReport({ client }: ExportClientReportProps) {
  const [showPreview, setShowPreview] = useState(false);
  const [copied, setCopied] = useState(false);

  const markdown = useMemo(() => generateMarkdown(client), [client]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = markdown;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [markdown]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="bg-white/[0.04] border border-white/[0.06] rounded-xl p-4"
    >
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-stone-300 text-xs font-semibold uppercase tracking-wider flex items-center gap-2">
          <FileText size={14} className="text-[#D4A853]" />
          Client Report
        </h3>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setShowPreview((p) => !p)}
            className="flex items-center gap-1.5 text-stone-400 hover:text-stone-200 transition-colors text-xs"
          >
            {showPreview ? <EyeOff size={12} /> : <Eye size={12} />}
            {showPreview ? 'Hide' : 'Preview'}
          </button>
        </div>
      </div>

      {/* Client summary */}
      <div className="flex items-center gap-3 mb-3 py-2 px-3 rounded-lg bg-white/[0.02]">
        <div className="w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold bg-[#D4A853]/20 text-[#D4A853] flex-shrink-0">
          {client.name.charAt(0)}
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-stone-200 text-sm font-medium truncate">{client.name}</p>
          <p className="text-stone-500 text-[10px]">{client.goal} &middot; {client.adherence}% adherence</p>
        </div>
      </div>

      {/* Preview */}
      <AnimatePresence>
        {showPreview && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: 'easeInOut' }}
            className="overflow-hidden"
          >
            <pre className="text-stone-400 text-[11px] leading-relaxed whitespace-pre-wrap bg-white/[0.02] border border-white/[0.06] rounded-lg p-3 mb-3 max-h-[280px] overflow-y-auto font-mono scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent">
              {markdown}
            </pre>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Copy button */}
      <button
        type="button"
        onClick={handleCopy}
        className="w-full py-2.5 rounded-lg font-semibold text-sm transition-all flex items-center justify-center gap-2"
        style={{
          backgroundColor: copied ? 'rgba(74, 222, 128, 0.2)' : 'rgba(212, 168, 83, 0.15)',
          color: copied ? '#4ade80' : '#D4A853',
          borderWidth: 1,
          borderColor: copied ? 'rgba(74, 222, 128, 0.3)' : 'rgba(212, 168, 83, 0.3)',
        }}
      >
        {copied ? <Check size={14} /> : <Copy size={14} />}
        {copied ? 'Copied!' : 'Copy to Clipboard'}
      </button>
    </motion.div>
  );
});
