import bpy,os,json,time,hashlib,gpu
from pathlib import Path
from mathutils import Vector
root=Path(os.environ['TROPHE_FACTORY_ROOT']).resolve(strict=True);out=root/'visual02-curl720-02';out.mkdir(exist_ok=False);lock=root/'pc-gpu-lock';lock.mkdir();(lock/'owner.json').write_text(json.dumps({'id':'ag2-visual02-curl720-02','pid':os.getpid(),'started_at':time.time()}));bpy.ops.wm.open_mainfile(filepath=str(root/'visual02-curl-v2-source02.blend'));s=bpy.context.scene;s.render.engine='BLENDER_EEVEE';s.render.resolution_percentage=100;s.render.image_settings.media_type='IMAGE';s.render.image_settings.file_format='PNG';s.frame_set(1)
for name,loc in [('front',(0,-4,1.2)),('back',(0,4,1.2)),('three-quarter',(2.6,-4.7,2))]:
 s.camera.location=loc;s.camera.rotation_euler=(Vector((0,0,.88))-s.camera.location).to_track_quat('-Z','Y').to_euler();s.camera.data.ortho_scale=2.1;s.render.resolution_x=720;s.render.resolution_y=900;s.render.filepath=str(out/(name+'.png'));bpy.ops.render.render(write_still=True)
s.camera.location=(2.6,-4.7,2);s.camera.rotation_euler=(Vector((0,0,.88))-s.camera.location).to_track_quat('-Z','Y').to_euler();s.camera.data.ortho_scale=3.65;s.render.resolution_x=1280;s.render.resolution_y=720
for frame in [1,37,73,127,180]:
 s.frame_set(frame);s.render.filepath=str(out/f'phase-{frame:03}.png');bpy.ops.render.render(write_still=True)
s.frame_start=1;s.frame_end=180;s.render.fps=30;s.frame_set(1);s.render.image_settings.media_type='VIDEO';s.render.ffmpeg.format='MPEG4';s.render.ffmpeg.codec='H264';s.render.ffmpeg.constant_rate_factor='HIGH';s.render.filepath=str(out/'motion-720.partial.mp4');bpy.ops.wm.save_as_mainfile(filepath=str(out/'curl.blend'));start=time.monotonic();bpy.ops.render.render(animation=True);elapsed=time.monotonic()-start;(out/'motion-720.partial.mp4').rename(out/'motion-720.mp4');(out/'result.json').write_text(json.dumps({'id':'ag2-visual02-curl720-02','blender':bpy.app.version_string,'build':bpy.app.build_hash.decode(),'engine':s.render.engine,'renderer':gpu.platform.renderer_get(),'resolution':[1280,720],'frames':180,'fps':30,'duration':6,'elapsed_seconds':elapsed,'source_sha256':hashlib.sha256((root/'visual02-curl-v2-source02.blend').read_bytes()).hexdigest(),'reviews':{'visual':'pending','technique':'pending'}},indent=2));(out/'terminal.json').write_text(json.dumps({'id':'ag2-visual02-curl720-02','pid':os.getpid(),'script_exit':0}));print('VISUAL02_CURL720_COMPLETE')
