import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';
import {drizzle} from 'drizzle-orm/node-postgres';
import {createPhotoFoodService} from '../../agents/coach-assistant/photo-food-service';
import {createOfflinePhotoFoodObservationPort} from '../../agents/coach-assistant/photo-food-observation';
import {createIsolatedPhotoFoodBoundary} from '../../agents/coach-assistant/photo-food-isolation';
import type {PhotoFoodOperation} from '../../agents/coach-assistant/photo-food-actions';
import type {PhotoFoodProposal} from '../../agents/coach-assistant/photo-food-contracts';

const target=new URL(process.env.DATABASE_URL??'about:blank');
if(process.env.CI!=='true'||process.env.GITHUB_ACTIONS!=='true'||process.env.CI_REAL_SUPABASE!=='1'||target.protocol!=='postgresql:'||target.hostname!=='127.0.0.1'||target.port!=='54322'||target.pathname!=='/postgres'||target.username!=='postgres'||target.password!=='postgres'||target.search||target.hash)throw Error('disposable_target_required');
const actor=process.env.COACH_SQL_ACTOR!,coach=process.env.COACH_SQL_COACH!,org=process.env.COACH_SQL_ORG!;for(const value of [actor,coach,org])assert.match(value,/^[a-f0-9-]{36}$/);
const pool=new Pool({connectionString:target.toString(),max:4,statement_timeout:5000}),database=drizzle(pool);const conversation=randomUUID(),attachment=randomUUID(),observation=randomUUID(),revision=randomUUID(),digest='a'.repeat(64);const actionIds:string[]=[],proposalIds:string[]=[],entryIds:string[]=[];
const scope={actorId:actor,subjectId:actor,organizationId:org,conversationId:conversation,attachmentId:attachment};
const port=createOfflinePhotoFoodObservationPort([{...scope,id:observation,revision,imageDigest:digest,foods:[{name:'Fixture rice',estimated_grams:100,estimated_calories:130,estimated_protein_g:2.7,estimated_carbs_g:28,estimated_fat_g:.3,estimated_fiber_g:.4,estimated_sugar_g:0,confidence:.7,source:'ai_estimate',accuracy_note:'Offline estimate; confirm portion.'}]}]);
const env={...process.env,COACH_ASSISTANT_ISOLATED_ENGINE_ENABLED:'1',COACH_ASSISTANT_ISOLATED_PHOTO_FOOD_ENABLED:'1',COACH_ASSISTANT_DATA_SOURCE:'authorized_records',VERCEL_ENV:'preview',TROPHE_ALLOW_PAID_AI:'0'};
let service:ReturnType<typeof createPhotoFoodService>,installed=false,check='setup';const pass=()=>process.stdout.write(JSON.stringify({event:'coach_photo_food_sql',check,outcome:'passed'})+'\n');
const header=()=>({version:'coach-assistant.v2' as const,conversationId:conversation,turnId:randomUUID()});const execute=(operation:PhotoFoodOperation,subjectId=actor,organizationId=org)=>service.execute({actorId:actor,subjectId,organizationId,operation,signal:new AbortController().signal});
async function propose(){const read=await execute({...header(),operation:'photo.food.read',attachmentId:attachment});assert.ok(read.ok&&'snapshot'in read);const item=read.snapshot.items[0];const result=await execute({...header(),operation:'photo.food.propose',attachmentId:attachment,observationId:read.snapshot.observationId,itemIndex:item.index,resourceVersion:item.version,after:{loggedDate:'2026-09-08',mealType:'lunch',grams:150}});assert.ok(result.ok&&'proposal'in result);proposalIds.push(result.proposal.id);return result.proposal;}
const apply=(p:PhotoFoodProposal,actionId=randomUUID()):Extract<PhotoFoodOperation,{operation:'photo.food.apply'}>=>{actionIds.push(actionId);return {...header(),operation:'photo.food.apply',proposalId:p.id,hash:p.hash,actionId,resourceVersion:p.resource.version,reviewed:true};};
async function main(){
 await pool.query(await readFile('db/isolated/coach-food-actions.sql','utf8'));await pool.query(await readFile('db/isolated/coach-photo-food-actions.sql','utf8'));await pool.query(await readFile('db/isolated/coach-private-attachments.sql','utf8'));await pool.query(await readFile('db/isolated/coach-photo-food-observations.sql','utf8'));installed=true;
 await pool.query("INSERT INTO private.coach_attachment_uploads(id,actor_id,subject_id,organization_id,conversation_id,request_id,bucket,object_path,mime,input_bytes,upload_token_hash,source_digest,normalized_digest,state,metadata,expires_at) VALUES($1,$2,$2,$3,$4,$5,'coach-attachments-ci',$6,'image/jpeg',100,$7,$8,$8,'available',$9::jsonb,clock_timestamp()+interval '10 minutes')",[attachment,actor,org,conversation,randomUUID(),`${org}/${actor}/${conversation}/${attachment}.jpg`,'b'.repeat(64),digest,JSON.stringify({mime:'image/jpeg',bytes:100,width:10,height:10})]);
 service=createPhotoFoodService(database,port,createIsolatedPhotoFoodBoundary(env,database,port,[scope]));
 check='review_then_exactly_one_write_receipt_readback';const p=await propose();assert.equal(p.before,null);assert.equal(p.after.grams,150);assert.equal(p.after.calories,195);const op=apply(p);const [a,b]=await Promise.all([execute(op),execute(op)]);assert.deepEqual(a,b);assert.ok(a.ok&&'receipt'in a);entryIds.push(a.refresh.entryId);assert.equal((await pool.query('SELECT id FROM public.food_log WHERE id=$1 AND user_id=$2',[a.refresh.entryId,actor])).rowCount,1);assert.equal((await pool.query('SELECT id FROM private.coach_action_receipts WHERE actor_id=$1 AND action_id=$2',[actor,op.actionId])).rowCount,1);pass();
 check='same_action_receipt_retry_without_duplicate';const recovered=await execute({...header(),operation:'photo.food.receipt',actionId:op.actionId});assert.deepEqual(recovered,a);assert.equal((await pool.query('SELECT id FROM public.food_log WHERE id=$1',[a.refresh.entryId])).rowCount,1);pass();
 check='wrong_owner_and_expired_attachment_fail_closed';const wrong=await execute({...header(),operation:'photo.food.read',attachmentId:attachment},coach);assert.ok(!wrong.ok&&wrong.error==='forbidden');await pool.query("UPDATE private.coach_attachment_uploads SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[attachment]);const expired=await execute({...header(),operation:'photo.food.read',attachmentId:attachment});assert.ok(!expired.ok&&expired.error==='expired');pass();
}
main().catch(error=>{process.stderr.write(JSON.stringify({event:'coach_photo_food_sql',check,outcome:'failed',...(typeof error?.code==='string'?{sqlstate:error.code}:{})})+'\n');process.exitCode=1;}).finally(async()=>{try{if(installed){const cx=await pool.connect();try{await cx.query('BEGIN');await cx.query('LOCK TABLE public.audit_log IN ACCESS EXCLUSIVE MODE');await cx.query('ALTER TABLE public.audit_log DISABLE TRIGGER audit_log_immutable');await cx.query("DELETE FROM public.audit_log WHERE actor_id=$1 AND action='photo_food_created' AND record_id=ANY($2::uuid[]) AND new_value->>'actionId'=ANY($3::text[])",[actor,entryIds,actionIds]);await cx.query('ALTER TABLE public.audit_log ENABLE TRIGGER audit_log_immutable');await cx.query('DELETE FROM private.coach_action_receipts WHERE actor_id=$1 AND action_id=ANY($2::uuid[])',[actor,actionIds]);await cx.query('DELETE FROM private.coach_action_proposals WHERE actor_id=$1 AND id=ANY($2::uuid[])',[actor,proposalIds]);await cx.query('DELETE FROM public.food_log WHERE user_id=$1 AND id=ANY($2::uuid[])',[actor,entryIds]);await cx.query('DROP TRIGGER coach_photo_food_profile_invalidate ON public.profiles; DROP TRIGGER coach_photo_food_client_invalidate ON public.client_profiles; DROP TRIGGER coach_photo_food_membership_invalidate ON public.organization_members');await cx.query('DROP TABLE private.coach_photo_food_observations; DROP FUNCTION private.coach_photo_food_observation_guard(); DROP FUNCTION private.coach_photo_food_no_truncate(); DROP FUNCTION private.coach_photo_food_auth_invalidate()');await cx.query('DELETE FROM private.coach_attachment_uploads WHERE id=$1 AND actor_id=$2',[attachment,actor]);await cx.query('DROP TABLE private.coach_attachment_uploads');await cx.query("ALTER TABLE private.coach_action_proposals DROP CONSTRAINT coach_action_proposals_action_check; ALTER TABLE private.coach_action_proposals ADD CONSTRAINT coach_action_proposals_action_check CHECK (action IN ('preference.update','food.quantity.update'))");await cx.query('ALTER TABLE private.coach_action_proposals DROP CONSTRAINT coach_action_proposals_envelope_check; ALTER TABLE private.coach_action_proposals ADD CONSTRAINT coach_action_proposals_envelope_check CHECK (jsonb_typeof(envelope)=\'object\' AND octet_length(envelope::text)<=4096)');await cx.query('DROP TRIGGER coach_food_entry_revision ON public.food_log; DROP FUNCTION private.advance_coach_food_entry_version(); DROP TABLE private.coach_food_entry_versions');await cx.query('COMMIT');pass();}catch(error){await cx.query('ROLLBACK');throw error;}finally{cx.release();}}}catch{process.stderr.write(JSON.stringify({event:'coach_photo_food_sql',check:'cleanup',outcome:'failed'})+'\n');process.exitCode=1;}await pool.end();});
